### PR TITLE
Fixed issue 1176

### PR DESCRIPTION
**Pull request by Alireza-Mim**
A quick hotfix for issue #1176. 
This may also fix any other issues with the key combination which are raised because of stripped Ctrl+ and Ctrl+Shift+ in Qt code.

### CODE REVIEW

**Comment by auchri** [comment]
Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

**Comment by Alireza-Mim** [comment]
Yes. I'm truly sorry. My first commit and I totally forgot :)

**Comment by auchri** [comment]
No problem, but please don't forget it next time :)

**Comment by Alireza-Mim** [comment]
@auchri  Looks like there is no easy way to change my commit message
Is there a shortcut for this? Or I should make a new commit?

P.S: Sorry for the mess

**Comment by auchri** [comment]
Yes, with the git shell it's not too hard: http://stackoverflow.com/a/179147/4752807

I'll include instructions to change the commit message soon :)

**Comment by Alireza-Mim** [comment]
@auchri 
Fixed the message. Thank you :)

**Comment by telegramdesktop** [comment]
@Alireza-Mim yet I'm not sure it won't be better to allow only this Zwj and Zwnj characters in this Ctrl+ and Ctrl+Shift+ combinations, because I don't quite understand why they were disabled (in German?) in the first place.

**Comment by telegramdesktop** [comment]
@Alireza-Mim also, should not it be fixed in qwidgetlinecontrol.cpp as well? For them to work in line input fields, like Search field.

**Comment by telegramdesktop** [comment]
(no need to make a Pull request, I'll add it, just interested, if it's working in Search field).

**Comment by Alireza-Mim** [comment]
I didn't check the search field at first. It's seems not working there either. 
Thanks for fixing it.

As I checked the discussions in the Qt bug tracker, in German language they didn't want to type anything using either Ctrl or Ctrl + Shift. Instead they just wanted Ctrl + Alt (Alt Gr). So without any additional checking for German keyboard in the code, they've just disabled the whole thing.

**Comment by Alireza-Mim** [comment]
I pulled and tested your change. 
The fix is working in the search field, like a charm. 

Thank you :)

**Pull request merged**
