### PR TITLE
building-xcode.md: remove gyp

### PR DESCRIPTION
**Pull request by a-x-**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Strange PR, if you remove gyp from the instruction, the later step with crashpad will fail

**Comment by a-x-** [comment]
Yep, Please help to complete update the manual

I don't know how you build it

**Comment by a-x-** [comment]
`gyp` is not used now as I know

**Comment by ilya-fedin** [comment]
> `gyp` is not used for tdesktop now as I know

Well, that's false

**Comment by a-x-** [comment]
so, we came back to issue.
Gyp installation is broken

**Comment by john-preston** [comment]
I've ran right now:
```
git clone https://chromium.googlesource.com/external/gyp
cd gyp
git checkout 9f2a7bb1
git apply ../patches/gyp.diff
```

on macOS and it ran without any issues 🤔

**Pull request closed without merging**
