### PR TITLE
Update stale.yml

### PR DESCRIPTION
**Pull request by SmartManoj**

### CODE REVIEW

**Comment by SmartManoj** [comment]
checks not necessary for an edit in .github folder.

**Comment by ilya-fedin** [comment]
The reason to have this bot is to close bug reports, feature requests and question no one interested for, this PR divides the stalebot mission by zero

**Comment by SmartManoj** [comment]
@ilya-fedin Exactly but it closes issues that people have interested in it (check the reactions to the current stale issues)

**Comment by SmartManoj** [comment]
Also, these labels are added by @Aokromes, so at least one people interested in it

**Comment by SmartManoj** [comment]
https://github.com/actions/stale/issues/202

**Comment by ilya-fedin** [comment]
> Exactly but it closes issues that people have interested in it (check the reactions to the current stale issues)

If someone really wants an issue to be open, he/she can just comment. If no one can comment, then these reactions are out-of-date anyway ;)

**Comment by SmartManoj** [comment]
No one should comment as +1 for enhancement.
Ignoring bug report is <no_word> 😶

**Comment by SmartManoj** [comment]
The checks stopped?

**Comment by ilya-fedin** [comment]
> No one should comment as +1 for enhancement.

I disagree, this is an old good method to check if anyone cares of this feature request.

**Comment by ilya-fedin** [comment]
> The checks stopped?

All issues were processed

**Comment by SmartManoj** [comment]
https://github.com/probot/ideas/issues/75

**Comment by SmartManoj** [comment]
https://github.com/cla-assistant/cla-assistant/issues/476

**Comment by john-preston** [comment]
We'll try with increased timeout.

**Review by expert1989 — COMMENTED** [review]
[0980811466]()

**Comment by SmartManoj** [comment]
@expert1989 ?

**Comment by ilya-fedin** [comment]
> @expert1989 ?

This is a chinese spambot I guess

**Pull request closed without merging**
