### PR TITLE
Update Fedora version

### PR DESCRIPTION
**Pull request by omkarnathsingh**
Working fine on Fedora 28.

### CODE REVIEW

**Comment by stek29** [comment]
Hm, I wonder if it also applies to Ubuntu 18.04.

**Comment by omkarnathsingh** [comment]
I personally use 18.04, its opening within seconds. I had tried Fedora 28 vanilla in VM, it was opening within seconds in that too. Not sure of those special people who are taking 1 hour to open it. It may their machine problem.

**Comment by stek29** [comment]
@omkarnathsingh it's not just "their machine problem" if there are a lot of "them", and if "native" builds have no issues.

**Comment by omkarnathsingh** [comment]
@stek29 I had used from https://github.com/telegramdesktop/tdesktop/releases/download/v1.2.17/tsetup.1.2.17.tar.xz . Thats native build or what? I am not aware of build process, sorry.

**Comment by stek29** [comment]
@omkarnathsingh by native builds I mean unofficial builds provided by distro maintainers

**Comment by omkarnathsingh** [comment]
I have another query. Ubuntu 12.04 has crossed End of Life, should we still display it in Readme as supported version?

**Comment by Aokromes** [comment]
well telegram still supports xp xd

**Comment by john-preston** [comment]
Thanks.

**Pull request merged**
