### PR TITLE
Fixing FFmpeg not playing videos/gifs/animated stickers on armhf and arm64 #6647

### PR DESCRIPTION
**Pull request by AliDjango**
by adding `--disable-neon` to FFMPEG configflags in snap config file
thanks to @ilya-fedin for finding [the fix](https://github.com/telegramdesktop/tdesktop/issues/6647#issuecomment-596870152)

### CODE REVIEW

**Comment by AliDjango** [comment]
lol.snap check failed because of a timeout. should be fine because I had nothing to do with sbt

**Comment by ilya-fedin** [comment]
> because of a timeout

no, because it can't fetch commit. Some strange github bug, but can be fixed by removing two last useless commits.

**Comment by AliDjango** [comment]
> no, because it can't fetch commit. Some strange github bug, but can be fixed by removing two last useless commits.

First it was updating apt sources and failed and the re run and this happened.
_I'm going to remove those two commits.I was lazy to revert :P_

**Comment by AliDjango** [comment]
@ilya-fedin whats going on now?

**Comment by ilya-fedin** [comment]
> whats going on now?

github just loves telegram :)

**Comment by AliDjango** [comment]
> github just loves telegram :)

Yeah of course, that is crystal clear.
Windows : https://github.com/telegramdesktop/tdesktop/actions/runs/53038286
linux : https://github.com/telegramdesktop/tdesktop/actions/runs/53096772
macOS : https://github.com/telegramdesktop/tdesktop/actions/runs/53038276
snap : https://github.com/telegramdesktop/tdesktop/actions/runs/53096775
@john-preston all of them were successful.if you want to make sure just rerun those test that are failing.

**Comment by AliDjango** [comment]
it's failing with that GitHub bug.
funny thing is that i used github website to edit the file(didn't even cloned it) lol

**Comment by john-preston** [comment]
So, I was told it won't link on aarch64.

**Comment by AliDjango** [comment]
> 
> 
> So, I was told it won't link on aarch64.

I guess it won't.we made a ticked in ffmpeg tracker.
don't merge yet until we find a workaround

**Comment by john-preston** [comment]
I've merged another one, with a patch. Thank you for the testing!

**Pull request closed without merging**
