### PR TITLE
qt config build type mismatch with -L

### PR DESCRIPTION
**Pull request by JayDi85**
Signed-off-by: Oleg Agafonov <jaydi85@gmail.com> (github: JayDi85)

### CODE REVIEW

**Comment by auchri** [comment]
Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

Instructions to change the commit message [here](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#change-commit-message-of-a-pushed-commit).

**Comment by auchri** [comment]
@JayDi85 you have to change the message of your **commit**, not the message of the pull request

**Comment by auchri** [comment]
:+1:

**Comment by JayDi85** [comment]
Sorry guys, I'm was wrong. Your script is correct. There are must be "-L" (big) -- it's add search library path for "-l" (small) files like "Gdi32".

**Pull request closed without merging**
