### PR TITLE
Add Sonnet for linux spellcheck

### PR DESCRIPTION
**Pull request by ilya-fedin**

### CODE REVIEW

**Comment by 23rd** [comment]
Can't build.
`./configure.sh -D TDESKTOP_API_TEST=ON -D DESKTOP_APP_USE_PACKAGED=OFF` gives me an error.
```
CMake Error at cmake/target_link_static_libraries.cmake:43 (target_link_libraries):
  Cannot specify link libraries for target "external_sonnet" which is not
  built by this project.
Call Stack (most recent call first):
  cmake/external/hunspell/CMakeLists.txt:24 (target_link_static_libraries)
```

Perhaps an instruction to build the static hunspell is missed.

**Comment by ilya-fedin** [comment]
Oops, there is typo
https://github.com/desktop-app/cmake_helpers/pull/9/commits/7e32d5358b29daaf745696ed978ac758bd17918c#diff-4795af30cc670e47ba215ac1777f13f8R24

**Comment by ilya-fedin** [comment]
fixed

**Comment by ilya-fedin** [comment]
> Perhaps an instruction to build the static hunspell is missed.

Yes, I can't build tdesktop statically even without hunspell, so I only tested static sonnet and added hunspell to build scripts by analogue. Hunspell build instruction probably will:
```
git clone https://github.com/hunspell/hunspell
cd hunspell
git checkout v1.7.0
autoreconf -vfi
./configure
make $MAKE_THREADS_CNT
sudo make install
cd ..
```
If this works, I can add this to building-cmake.md in this pr

**Comment by kirsan31** [comment]
Theoretically we can use Sonnet (with hunspell) on windows 7 too. But building it statically on windows not a trivial thing :(

**Comment by ilya-fedin** [comment]
> But building it statically on windows not a trivial thing :(

What do you mean? Anyway, this pr adds custom build scripts for sonnet and, maybe, they can made this easier.

> Theoretically we can use Sonnet (with hunspell) on windows 7 too.

Theoretically we can even enable ISpellChecker in Sonnet. But Sonnet can't delete words from custom dictionaries, that's why I took only GuessLanguage from Sonnet.

**Comment by kirsan31** [comment]
> What do you mean?

I doubted about [Build instructions for Visual Studio 2019](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md). When I was building (in 2018) Sonnet on windows  to use it with TD in Visual Studio. It took a lot of time for me and some manual steps (including simple code modifications, because officially sonnet needed QT 5.8.0 (at least at 2018))... May be things changed from those times? And/or may be it was to my poor (if any? :) ) Linux knowledge...

**Comment by 23rd** [comment]
> fixed

Now I get this.

  <details>
    <summary>Terminal output</summary><p>

    /usr/include/x86_64-linux-gnu/bits/string3.h:81: warning: memset used with constant zero length parameter; this could be due to transposed parameters
    ../cmake/external/sonnet/CMakeFiles/external_sonnet.dir/__/__/__/Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp.o: In function 'HunspellDict::HunspellDict(QString const&, QString)':
    ./Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp:72: undefined reference to 'Hunspell::add_with_affix(std::string const&, std::string const&)'
    ./Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp:77: undefined reference to 'Hunspell::remove(std::string const&)'
    ./Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp:79: undefined reference to 'Hunspell::add(std::string const&)'
    ../cmake/external/sonnet/CMakeFiles/external_sonnet.dir/__/__/__/Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp.o: In function 'HunspellDict::isCorrect(QString const&) const':
    ./Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp:112: undefined reference to 'Hunspell::spell(std::string const&, int*, std::string*)'
    ../cmake/external/sonnet/CMakeFiles/external_sonnet.dir/__/__/__/Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp.o: In function 'HunspellDict::suggest(QString const&) const':
    ./Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp:133: undefined reference to 'Hunspell::suggest(std::string const&)'
    ../cmake/external/sonnet/CMakeFiles/external_sonnet.dir/__/__/__/Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp.o: In function 'HunspellDict::addToPersonal(QString const&)':
    ./Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp:157: undefined reference to 'Hunspell::add(std::string const&)'
    ../cmake/external/sonnet/CMakeFiles/external_sonnet.dir/__/__/__/Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp.o: In function 'HunspellDict::addToSession(QString const&)':
    ./Telegram/ThirdParty/sonnet/src/plugins/hunspell/hunspelldict.cpp:175: undefined reference to 'Hunspell::add(std::string const&)'
    collect2: error: ld returned 1 exit status
    make[2]: *** [bin/Telegram] Error 1
    make[1]: *** [Telegram/CMakeFiles/Telegram.dir/all] Error 2
    make: *** [all] Error 2


</p></details>

```
gcc --version
gcc (Ubuntu 8.3.0-16ubuntu3~14.04.2) 8.3.0
```

**Comment by ilya-fedin** [comment]
@23rd should be fixed now

**Pull request closed without merging**
