### PR TITLE
Update building-msvc.md

### PR DESCRIPTION
**Pull request by Neurotoxin001**
Add some more requirements because without them users will get errors

### CODE REVIEW

**Comment by john-preston** [comment]
If this line is done when you build:

https://github.com/telegramdesktop/tdesktop/blame/dev/docs/building-msvc.md#L56

There is no need to add Python27, jom and yasm to PATH.

**Comment by Neurotoxin001** [comment]
> There is no need to add Python27, jom and yasm to PATH.

I got errors like this if I don't add them to PATH (on Windows 10 LTSC 1809 at least)
image

And
> "python" not recognized as a command

**Comment by john-preston** [comment]
@Neurotoxin001 Well, then you didn't run the command I mentioned above in the root of the build path - it adds python and yasm and jom to PATH.

**Comment by Sventra** [comment]
I had no issues with the build by following all the steps in the documentation

**Comment by Neurotoxin001** [comment]
> UPD2: But there is another question then — why gyp and Ninja not in this first line with all other PATH's?

I got a problem because I don't have a Git and 

> git clone --recursive https://github.com/telegramdesktop/tdesktop.git

is going right after first line with "SET PATH". After installing Git I start from the second line. That's why I have errors in next steps.

**Comment by john-preston** [comment]
@Neurotoxin001 Ok, so you can just leave the "install git" point and remove the path points, because if you perform all the commands one after another you won't have any errors.

**Comment by john-preston** [comment]
Ok, thanks!

**Pull request merged**
