### PR TITLE
lib_export: use includes paths as defined per platform

### PR DESCRIPTION
**Pull request by 3v1n0**
Fixes the build failures locally (and hopefully) in travis

### CODE REVIEW

**Comment by stek29** [comment]
Thank you!

**Comment by vhborges** [comment]
After this commit I cannot build Telegram anymore, when running gyp/refresh.sh I get this error:

> gyp: Undefined variable build_defines in lib_export.gyp

Is there something else to be updated?

**Comment by 3v1n0** [comment]
@vhborges try to pass a -Dbuild_defines='' to the gyp commandor that could be defined empty in the `lib_export.gyp` file too as other variables

**Comment by john-preston** [comment]
This broke default Linux build and broke macOS build completely without a fast fix, because "mac_bundle" properties can't be set in "shared_library" targets :(

**Pull request merged**
