### PR TITLE
Add Platform::AutostartSupported

### PR DESCRIPTION
**Pull request by ilya-fedin**

### CODE REVIEW

**Comment by john-preston** [comment]
Thanks!

**Comment by c0re100** [comment]
Seems missing `base/platform/base_platform_info.h` header

**Comment by ilya-fedin** [comment]
> Seems missing `base/platform/base_platform_info.h` header

What are you talking about?

**Comment by c0re100** [comment]
> > Seems missing `base/platform/base_platform_info.h` header
> 
> What are you talking about?

Oh sorry, I mean specific_win.cpp is missing `base/platform/base_platform_info.h` header
Cause 
https://github.com/ilya-fedin/tdesktop/blob/736cad3aa8a95faacee6f9a35a96917cba632334/Telegram/SourceFiles/platform/win/specific_win.cpp#L384 is using Platform class.

**Pull request merged**
