### PR TITLE
Update AppStream metadata with information about releases and keywords

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by grulja** [comment]
This will solve https://github.com/telegramdesktop/tdesktop/issues/5740.

**Comment by john-preston** [comment]
@grulja It solves only one particular version :( there was such pr already, but it is required for me to be able to fill changelog only in one place and then use in buildscripts, now it is changelogs.txt

**Comment by grulja** [comment]
I was hoping you can do this one simple step manually, but I believe this can be also somehow scripted or a tool written to do that. I'll look what can be done about that. Having version and changelog in AppStream metadata is a good step towards users, they will see it in gnome-software or in KDE plasma-discover.

**Comment by grulja** [comment]
I was thinking about modifying your python scripts, but given I have zero knowledge of python and limited time, I will just keep patching the appstream metadata in the Flatpak version of Telegram.

**Comment by john-preston** [comment]
@grulja I hope to reach that. Still hope 😭

**Pull request closed without merging**
