### PR TITLE
Add symbolic app icon

### PR DESCRIPTION
**Pull request by jsparber**
GNOME Shell uses the symbolic icon in some places.

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Can you explain better why should this be merged? As-is it's not clear what this change would affect.

**Comment by jsparber** [comment]
> Can you explain better why should this be merged? As-is it's not clear what this change would affect.

GNOME uses the symbolic icon in the topbar next to the app menu and in notifications when the app doesn't provide a icon for the notification.

**Comment by ilya-fedin** [comment]
So you're proposing a window icon change. I'm not sure that's allowed...
@john-preston what do you think?

**Comment by jsparber** [comment]
> So you're proposing a window icon change. I'm not sure that's allowed... @john-preston what do you think?

No it's not. It just uses the symbolic icon in specific places, defined by the platforms theme. For example currently in GNOME the hicolor icon is used in the top bar but made monochrome, because it Telegram doesn't provide a symbolic variant and it would look bad on the platform. 

How it will look like
image

**Comment by ilya-fedin** [comment]
You say it's not but I see on your screenshot that the window icon is changed

**Comment by ilya-fedin** [comment]
You say it's not but I see on your screenshot that the window icon is changed

**Comment by jsparber** [comment]
> You say it's not but I see on your screenshot that the window icon is changed

This is not the window icon, it's the icon used in the topbar.

Btw this is how it looks currently:
image

**Comment by ilya-fedin** [comment]
This is the same thing, it's just you call it an other way

**Comment by ilya-fedin** [comment]
This is the same thing, it's just you call it an other way

**Comment by john-preston** [comment]
I've added our svg icon to the repository:

https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/icons/tray_monochrome.svg

Maybe it could be used instead?

**Comment by ilya-fedin** [comment]
Please rebase rather than merging

**Comment by jsparber** [comment]
> Please rebase rather than merging

Sorry about that. I updated the commit using the icon you added.

**Comment by ilya-fedin** [comment]
@john-preston you maybe (unless you don't want this for official builds) merged this too early as the PR doesn't contain code to install the icon for official build

**Comment by jsparber** [comment]
> @john-preston you maybe (unless you don't want this for official builds) merged this too early as the PR doesn't contain code to install the icon for official build

what do you mean?

**Comment by ilya-fedin** [comment]
Official build copies the icons in runtime with the code in specific_linux.cpp. This code is no-op for the official build.

**Pull request merged**
