### PR TITLE
Improve XCode.md format and readability

### PR DESCRIPTION
**Pull request by Bl4ckc4t**
Fix some format, add warning on file hierarchy, fix typo and create list for readability.

### CODE REVIEW

**Comment by auchri** [comment]
Hi, thanks for the pr! :+1: 

I've added some comments, please correct them :)

**Comment by DaFri-Nochiterov** [comment]
@auchri, what's going on? :D 
[17 comments](http://www.clipular.com/c/6562858488823808.png?k=GIIkFdIt9iGqGgCWxAGM88cV9-M)

**Comment by Bl4ckc4t** [comment]
I've commited spaces fix. I'm not sure how to process your comments so hope what iI did is fine.

**Comment by auchri** [comment]
Looks good :+1: 
Please squash the commits: http://stackoverflow.com/a/5201642/4752807

**Comment by Bl4ckc4t** [comment]
Squashed ! Sorry for the bother, first contribution.

**Comment by telegramdesktop** [comment]
Thanks!

**Pull request merged**
