### PR TITLE
disabling notifications now disables sound too

### PR DESCRIPTION
**Pull request by Royal2000H**
In reference to issue #1615.

Please note, this was not tested as I do not currently have a build environment set up. It should be extremely quick and easy to test if the build environment is already configured.

### CODE REVIEW

**Comment by telegramdesktop** [comment]
I don't like it that way :( If you go to settings and disable just the popup notifications it will disable sound as well -- but they are different checkboxes, you can disable them separately and it is not looking good, when changing one checkbox automatically checks another.

**Comment by Royal2000H** [comment]
When you disable the notifications, it also disables "Sender's name" and "Message Preview" so it's not that different for the user. It only makes sense for the user to have a way to disable all notifications in one click.

If you disagree with this solution, how about a solution that clicking "Disable Notifications" in the tray would also disable Sound? So in the Settings menu, disabling Desktop notifications won't do anything but in the tray, disabling notifications will also disable sound.

**Comment by telegramdesktop** [comment]
@Royal2000H yes, this could be done, but in more complicated way. If you click in tray Disable notifications and then Enable notifications they should return to exact same state as they were before. So the sound settings should be saved in some way just for this switch in the tray icon menu. I'll think about that.

**Comment by john-preston** [comment]
This finally should work :)

**Pull request closed without merging**
