### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raghavgururajan**
Make a section for GNU/Linux distributions.

### CODE REVIEW

**Comment by Aokromes** [comment]
i don't think it will be added, linux distributions makes changes creating bug no present on official revisions.

**Comment by ilya-fedin** [comment]
> i don't think it will be added, linux distributions makes changes creating bug no present on official revisions.

\+1, it is worth to recommend only official builds. Debian maintainer is patching tdesktop very heavy, which results in different behavior.

**Comment by ilya-fedin** [comment]
And your guix packaging of tdesktop is very poor (sorry) from what I've seen... You added a lot of unneeded libraries as dependencies.

**Comment by raghavgururajan** [comment]
No worries! I close this.

**Pull request closed without merging**
