### PR TITLE
Have full path to the binary in .desktop file

### PR DESCRIPTION
**Pull request by ilya-fedin**
Depends on https://github.com/desktop-app/lib_base/pull/144

### CODE REVIEW

**Comment by xvitaly** [comment]
Hardcoding paths is a very bad practice.

**Comment by ilya-fedin** [comment]
@xvitaly hardcoding?

**Comment by xvitaly** [comment]
> @xvitaly hardcoding?

`/usr/bin/telegram-desktop` is hardcoded path. `telegram-desktop` is always preferred.

**Comment by ilya-fedin** [comment]
I don't know for who it's preferred, I heard an opinion it's a security problem to not to have full path to the binary in .desktop file. Anyway, this is not something I care about, feel free to submit a better PR to avoid creation of the URL scheme handler file that won't break official binary (just #ifndef'ing related code is not better of course).

**Pull request merged**
