### PR TITLE
Migrate from qt_static_plugins.cpp to the Qt6-pregenerated initializators 

### PR DESCRIPTION
**Pull request by ilya-fedin**
Depends on https://github.com/desktop-app/cmake_helpers/pull/284, https://github.com/desktop-app/codegen/pull/17

### CODE REVIEW

**Comment by novomesk** [comment]
I built the debug `Telegram.exe` on Windows from git and observed that AVIF, HEIC, JXL plug-ins no longer work.

When I move `Q_IMPORT_PLUGIN(QAVIFPlugin)` from `tdesktop\cmake\external\kimageformats\init.cpp` back to `tdesktop\cmake\external\qt\qt_static_plugins\qt_static_plugins.cpp`
then AVIF images work again.

**Comment by ilya-fedin** [comment]
looks like I forgot to do the STATIC -> OBJECT replacements

**Comment by ilya-fedin** [comment]
Can you check whether https://github.com/ilya-fedin/cmake_helpers/commit/44d83fb188fc9aee165cd5e477f089508a8aa560 fixes the problem?

**Comment by novomesk** [comment]
> Can you check whether [ilya-fedin/cmake_helpers@44d83fb](https://github.com/ilya-fedin/cmake_helpers/commit/44d83fb188fc9aee165cd5e477f089508a8aa560) fixes the problem?

Still doesn't work for me.

**Comment by ilya-fedin** [comment]
that's sad

**Comment by novomesk** [comment]
When I used `add_library(external_kimageformats STATIC)`

and 

```
nice_target_sources(external_kimageformats ${CMAKE_CURRENT_SOURCE_DIR}
PUBLIC
    init.cpp
)
```

it started to work again.

**Comment by ilya-fedin** [comment]
That's unlikely to be the right fix, this likely transmits the source to the targets dependent on this one that can have any compile definitions, include directories, linked libraries

**Comment by ilya-fedin** [comment]
This one works on Linux at least
https://github.com/desktop-app/cmake_helpers/pull/292

**Comment by novomesk** [comment]
> This one works on Linux at least
> [desktop-app/cmake_helpers#292](https://github.com/desktop-app/cmake_helpers/pull/292)

Works also on Windows! Thx.

**Comment by ilya-fedin** [comment]
Thank you for spotting this early

**Pull request merged**
