### PR TITLE
Use LXQt's StatusNotifierItem implementation instead of appindicator

### PR DESCRIPTION
**Pull request by ilya-fedin**

### CODE REVIEW

**Comment by magnus-gross** [comment]
What is the advantage of using this?

**Comment by ilya-fedin** [comment]
> What is the advantage of using this?

appindicator depends on gtk and doesn't have the full support of SNI. This change fixes all the tray issues in flatpak and provides a full control on using the API, including a proper support of indicator-application-service and using of the system hidpi svg icons without converting (enables by an environment variable currently)
+ I added the use of Ui::PopupMenu for XEmbed tray, which solves the issue with theming of the tray menu

**Comment by ilya-fedin** [comment]
In other words, this fixes:
https://github.com/telegramdesktop/tdesktop/issues/7115
https://github.com/telegramdesktop/tdesktop/issues/3216 (when the environment variable is set)
https://github.com/telegramdesktop/tdesktop/issues/5452 (Ui::PopupMenu uses open sans, as the whole Telegram)
https://github.com/telegramdesktop/tdesktop/issues/4059 and it's duplicate https://github.com/telegramdesktop/tdesktop/issues/4339

**Comment by john-preston** [comment]
Ok, let's try that.

**Comment by ugtar** [comment]
Unfortunately since this change (i think) we no longer have unread message counts in the app icon in ubuntu's (18.04) dock (or generic dash to dock), unless there is some workaround

**Comment by ilya-fedin** [comment]
> Unfortunately since this change (i think) we no longer have unread message counts in the app icon in ubuntu's (18.04) dock (or generic dash to dock)

Why? :open_mouth:

**Comment by ugtar** [comment]
well i could be wrong, but since upgrading to 1.9.9 i've noticed the unread badge doesn't appear in the dash icon anymore, I'm just guessing it has something to do with the change in notification mechanism

**Comment by ilya-fedin** [comment]
> but since upgrading to 1.9.9

this pr was merged after 1.9.9. Do you using telegram from snap?

**Comment by ugtar** [comment]
@ilya-fedin yes i use the snap. you're right it's not specifically this pr. sorry to make noise here. i thought there were several commits related to handling notifications and using qt abstractions rather than native calls in general, etc, but maybe i'm mistaken. It could be the notification badge thing is just a regular regression. in that case maybe i'll open an issue

**Comment by ugtar** [comment]
i should point out though, that in terms of #7115 which this commit should fix, while i don't have an issue seeing the icon, as mentioned in that bug the unread count badge is also missing.  I'm currently running snap from the edge channel (g6cf9157fb), which includes this commit, and it doesn't seem to have fixed that at least (the badge is still missing from the icon)

**Comment by ilya-fedin** [comment]
> yes i use the snap

can you tell which name has the desktop file of the snap?

**Comment by ugtar** [comment]
bleh sorry, i see i misread--#7115 is talking about the task tray but i'm looking at the dash2dock icon. please excuse me i'll open an issue. sorry for the noise

**Pull request merged**
