### PR TITLE
Notification over video

### PR DESCRIPTION
**Pull request by programcoder**
Added game and borderless app configuration, doesn't contain strings for ALL languages... need to add that part

Original Configuration
original

Modified configuration
modified

### CODE REVIEW

**Comment by Mackoman** [comment]
Hi
I would like to contact you. i need help with code.
@radio44

**Comment by Mackoman** [comment]
forgive me if I insist , but I would like to get in touch with you .

**Comment by programcoder** [comment]
@Mackoman Yes, you could send me a mail at foodman123321@gmail.com

**Comment by Mackoman** [comment]
hi tanks i send you email

**Comment by telegramdesktop** [comment]
Settings become to complicated. You want an option to _show_ them over games etc?

**Pull request closed without merging**
