### PR TITLE
Gnome Shell Duplicates bug fix

### PR DESCRIPTION
**Pull request by kanishkablack**
Telegram Desktop Developer Certificate of Origin

By making a contribution to this project, I certify that:

(a) The contribution was created in whole by me or is based upon
    previous work that, to the best of my knowledge, is in the
    public domain and I have the right to put it in the public domain.

(d) I understand and agree that this project and the contribution are
    public and that a record of the contribution (including all
    metadata and personal information I submit with it, including my
    sign-off) is maintained indefinitely and may be redistributed.

(e) I am granting this work into the public domain.

Signed-off-by: Anwesh <anwesh@gmx.com> (github: kanishkablack)

### CODE REVIEW

**Comment by telegramdesktop** [comment]
Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

**Comment by telegramdesktop** [comment]
Thanks for your fix.

**Comment by telegramdesktop** [comment]
@kanishkablack just for the future pull requests, this "Signed-off-by:" line is supposed to be in the end of the commit message, not in the description of the pull request here :)

**Comment by kanishkablack** [comment]
my bad, i didn't check the policy before pulling request.

**Pull request merged**
