### PR TITLE
Update changelog.txt

### PR DESCRIPTION
**Pull request by PeterMX**
Fixed a typo.

Signed-off-by: Uriel Castro Hernandez <urychdz@yandex.com> (github: PeterMX)

### CODE REVIEW

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

**Comment by PeterMX** [comment]
Is it OK now?

**Comment by auchri** [comment]
No, you have to change the message of your [commit](https://github.com/telegramdesktop/tdesktop/pull/3858/commits/40f5f4bb07cad8b694ad519b29b3eafd5b0ba9ed) as explained [here](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#change-commit-message-of-a-pushed-commit).

**Comment by stek29** [comment]
You haven't changed commit message, you've reviewed your own pull request.

**Comment by auchri** [comment]
Fixed by https://github.com/telegramdesktop/tdesktop/commit/7f776c70dbc51978c833d2dfc2f6d92eba65c1d9.

**Pull request closed without merging**
