### PR TITLE
Build docs

### LINKED ISSUE #1373: Build instructions for qmake
Since all IDEs depend on qmake invocations, the obvious way to build with only qmake is missing from the build descriptions.

Explanations on which buttons to click don’t make mature developers happy. Even less so people who want to package the program.

### PR DESCRIPTION
**Pull request by hobarrera**
Add documentation on how to build using qmake. I based these ENTIRELY on the ArchLinux package, so all real credit goes to them.

I also tidied up all build instructions and moved that into `/doc`, just for tidiness.

Closes #1373

### CODE REVIEW

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.
Also squash your commits to a single commit.

**Comment by hobarrera** [comment]
Sorry, I though I had looked at the contribution policy. Looks like I was mistaken.

Does the squash policy apply if each commit does something clearly different? I assumed that's for scenarios like:

    Fix bug 999
    Fix typo in last commit
    Fix bug 999 (again)

Should I still squash these?

**Comment by auchri** [comment]
No, doesn't matter :)

**Comment by hobarrera** [comment]
I just rebased this onto the latest master, since there were merge conflicts.

**Comment by telegramdesktop** [comment]
Well. But I'm afraid this won't build anymore, now with static openssl linking %)

**Pull request merged**
