### PR TITLE
feat: add setting checkbox to change messages width wide/tight

### LINKED ISSUE #2060: Allow to resize message block in chat window
Long messages has small width and large height, like a newspaper column. Sometimes It's hard to read such messages, also they take a lot of space on screen and make chat history less usable for me. Besides as a programmer I often send a code snippets in telegram, and it is practically impossible to read them because of small message width. 

 
### Steps to reproduce

Open chat window
### Expected behaviour

User can change width of message with mouse
### Actual behaviour

Message width is fixed
### Configuration

**Operating system:**
Windows
**Version of Telegram Desktop:**
0.9.49

### PR DESCRIPTION
**Pull request by kudlatyamroth**
Fixes #2060

This PR add setting checkbox in Chat Settings section.
If checkbox is checked, messages in chat doesn't have limit on width beside chat own width.
If checkbox is unchecked, messages width behave like now.

The default is unchecked to preserve default settings.

This is how it looks like when it is enabled:
chat_settings

chat_messages

P.S. If something is wrong, sorry because my last time with C++ was 15 years ago... Now it looks strange to me...

### CODE REVIEW

**Comment by kudlatyamroth** [comment]
updated to latest dev :)

**Comment by danwalmsley** [comment]
This is a much needed feature, probably off by default, but much needed for dev teams that use telegram

**Comment by john-preston** [comment]
I've done something similar for the case from your screenshot but without additional settings.

Note that per [contributing guidelines](https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md#what-contributions-are-accepted) we generally don't merge PRs that introduce new UI elements, including settings.

With the current solution done in https://github.com/telegramdesktop/tdesktop/commit/07e3671ca8e61e2d9a972c19c520d16077b89aa0 the monospace blocks (both `pre` and `code` if they take the whole paragraph) may extend the message bubble beyond st::maxMsgWidth limit.

**Comment by kudlatyamroth** [comment]
@john-preston but PRs with disabling st::maxMsgWidth for all messages were declined, so i hope so that this with config will have more chance to be merged.
As we know that mac client don't have this limit...
Wouldn't be great to have that option, so users can choose if they want full width or limited?

**Comment by grokys** [comment]
It's a shame this wasn't accepted. I'd really like messages to take more than ~15% of my screen width:

image

**Comment by kudlatyamroth** [comment]
@grokys if you want i created AUR package: https://aur.archlinux.org/packages/telegram-desktop-wide/

**Comment by grokys** [comment]
Thanks @kudlatyamroth but I'm on Windows. Maybe I'll have to do my own build :/

**Pull request closed without merging**
