### PR TITLE
added Polish translation file

### PR DESCRIPTION
**Pull request by Morgaroth**

### CODE REVIEW

**Comment by clash82** [comment]
Hey @Morgaroth, what's the progress of this PR? is there a chance to see Polish language in Telegram? ;-)

**Comment by garex** [comment]
@clash82 PR contains ocnflicts. Also as I see now, Telegram is not truly opensource project, so it's unfriendly to localizations. Especially to non-english-like.

**Comment by bil-elmoussaoui** [comment]
@garex telegram is not TDesktop, TelegramDesktop is made by community...

**Comment by garex** [comment]
@bil-elmoussaoui click "About" ))

**Comment by clash82** [comment]
@garex ok, but besides merge conflicts I was wondering if something else stands in the way of adding Polish language?

ping @Morgaroth

**Comment by Morgaroth** [comment]
I don't know if sth stands in the way of polish in TDesktop, I tried to build environment for building tdesktop, but I could not because some errors with selfcompiled dependencies I encountered.
Today, I have not enough time for developing PR :disappointed:

**Comment by telegramdesktop** [comment]
Languages are not managed from here, sorry.

**Pull request closed without merging**
