### PR TITLE
Added Korean Language(Full Translated)

### PR DESCRIPTION
**Pull request by itstake**

### CODE REVIEW

**Comment by itstake** [comment]
@garex plz read new pull request, thanks!
https://github.com/telegramdesktop/tdesktop/pull/383

**Comment by garex** [comment]
Also to add new lang you should change 3 files and add one:

    modified:   SourceFiles/lang.h
    new file:   SourceFiles/langs/lang_ru.strings
    modified:   SourceFiles/telegram_linux.qrc
    modified:   Telegram.pro

See #366

**Comment by itstake** [comment]
@garex ok, i commited

**Comment by garex** [comment]
@itstake where? I dont' see anything in #383 

Btw, may be you rebase this PR and delete all others?

**Comment by itstake** [comment]
@garex now commited, sorry :(

**Comment by garex** [comment]
Aaa.. It's already "unknown".. Also we have now two Korean langs — may be you need contact each other to select best translations? To someway cross-review. Then I think it will be best lang here.

**Comment by garex** [comment]
Oh no!.. Dont' add Russian lang :) Just add all needed links to Korean lang. As it will be many merge conflicts.

**Comment by itstake** [comment]
@garex Ah, ok. i removed.
and I will contact other language maker, thanks for advice!

**Pull request closed without merging**
