### PR TITLE
Fix Tray Icon in Mate Desktop

### PR DESCRIPTION
**Pull request by raonyguimaraes**
This will fix the tray icon in Mate Desktop Environment.

### CODE REVIEW

**Comment by raonyguimaraes** [comment]
This is how it looks right now:
telegram_tray_icon

**Comment by telegramdesktop** [comment]
Thank you!

So, the Qt implementation of tray icon does not work in Mate as well.. Did you test it?

If so, please read the [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md) and sign off your pull request as it is described there.

**Comment by dlussky** [comment]
Interesting, I'm using Mate, and my tray icon is just fine.
Mate Telegram icon screenshot
*Linux Mint 17.3

**Comment by DaFri-Nochiterov** [comment]
@dlussky, same

**Comment by raonyguimaraes** [comment]
I'm not the only one with this problem:

http://simon.aldrich.eu/blog/2016/01/telegram-tray-notification-icon-mate/

I will try to test it in an isolated environment.

**Comment by dlussky** [comment]
@raonyguimaraes what QT version are you using? It works fine in 4.8.6, then they break it somewhere along 5.x, and then fixed it in 5.4.2

**Comment by raonyguimaraes** [comment]
qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
Telegram Desktop 0.9.18

**Comment by raonyguimaraes** [comment]
After chasing this bug down I discovered that cleaning my home folder did fix the icon.

Sorry I will close this one ...

**Pull request closed without merging**
