### PR TITLE
New define: TDESKTOP_DISABLE_UNITY_INTEGRATION

### PR DESCRIPTION
**Pull request by eegorov**
Make possible build on system without unity (like Gentoo)

### CODE REVIEW

**Comment by eegorov** [comment]
Make possible build on system without unity (like Gentoo)

**Comment by auchri** [comment]
The new flag should also added to the travis build ([here](https://github.com/telegramdesktop/tdesktop/blob/master/.travis.yml) and [here](https://github.com/telegramdesktop/tdesktop/blob/master/.travis/build.sh#L78)).

**Comment by eegorov** [comment]
I make that. But I do not know how chech this.

**Comment by auchri** [comment]
looks good :+1:

**Comment by john-preston** [comment]
Better to make one commit only (squash).

**Comment by eegorov** [comment]
Done

**Pull request merged**
