### PR TITLE
Make build scripts a bit more configurable

### PR DESCRIPTION
**Pull request by mymedia2**
This adds some GYP variables (cpu_type, bitness, qt_loc, use_common_libs, etc.) to affect build configuration. All additional features are available when the corresponding flag is set. Default behavior is untouched (I hope so).

### CODE REVIEW

**Comment by john-preston** [comment]
@mymedia2 I’m afraid it’ll have to wait till the next release, because it has a lot of gyp changes :( It should happen in October.

**Comment by mymedia2** [comment]
@john-preston, okay, I'll refine the pull request to that time, at least it should pass CI

**Comment by xvitaly** [comment]
I think all this GYP scripts should be removed completely. We can take plain Cmake build script from Kepka fork.

**Comment by john-preston** [comment]
@xvitaly Does this config offer the same static builds with no more runtime dependencies than the current build on all three systems?

**Comment by xvitaly** [comment]
> Does this config offer the same static builds with no more runtime dependencies than the current build on all three systems?

You can forward `-DUSE_BUNDLED=1` to use bundled dependencies.

**Comment by vitlav** [comment]
> @xvitaly Does this config offer the same static builds with no more runtime dependencies than the current build on all three systems?
Can we have two build system? gyp based for static build for all three systems and cmake based for build with system libs?
For instance, I maintain cmake scripts for the official sources (this repo).

**Comment by john-preston** [comment]
@vitlav We can. But someone should maintain the second.

**Comment by Johnnynator** [comment]
@vitlav You are not the only one doing that. @msva for their gentoo overlay and I for @void-linux do currently also maintain a cmake based build system, but neither of us hold full copy right of it and therefore it can't be added into this repo.

**Comment by john-preston** [comment]
Doesn't apply after the new submodules were introduced :(

**Comment by john-preston** [comment]
This will become obsolete once we switch to CMake.

**Pull request closed without merging**
