### PR TITLE
Add option to close Telegram when Escape is pressed

### PR DESCRIPTION
**Pull request by splintor**
Should fix https://github.com/telegramdesktop/tdesktop/issues/1367

Missing settings string translations

### CODE REVIEW

**Comment by auchri** [comment]
I think this would be a nice addition :+1:

**Comment by splintor** [comment]
Any news?

**Comment by auchri** [comment]
@john-preston

**Comment by john-preston** [comment]
@auchri Perhaps after the settings are redesigned this option will be added. Right now the settings page is already too complex, so I don't want to fill it with additional controls for different minor settings.

**Comment by splintor** [comment]
@john-preston If this is the problem, can we at least add the option without adding the change in the Settings UI, so those who desperately want this option will be able to have it?

**Comment by splintor** [comment]
Can you please explain why won't you mergeg my pull request? I really love Telegram and this is the only thing that bugs me (and others).

**Comment by john-preston** [comment]
@splintor Because the settings are different now and this pr is not mergeable anyway. Also a checkbox in settings for that is not an option right now as I've mentioned above. Some way of geek-only settings file should be added for such things I guess.

**Comment by splintor** [comment]
@john-preston If I file another PR that used a "geek-only settings file" for that, will you reconsider merging it?

**Comment by stek29** [comment]
@splintor If you add "geek-only settings file" I'm 99% sure it would be merged, because lots of issues aren't fixed to avoid settings cluttering.

**Pull request closed without merging**
