### PR TITLE
fix: media show in folder

### PR DESCRIPTION
**Pull request by zunsthy**

### CODE REVIEW

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See travis build)

**Comment by zunsthy** [comment]
I've added the signature : )

**Comment by auchri** [comment]
There's a typo in your commit message 🙈

**Comment by zunsthy** [comment]
I'm sorry that I'm poor in English and can contribute the sentence with simple words : (

**Comment by john-preston** [comment]
Thank you for your help!

**Pull request merged**
