### PR TITLE
Add support for open with on linux

### PR DESCRIPTION
**Pull request by ilya-fedin**

### CODE REVIEW

**Comment by magnus-gross** [comment]
Great stuff! Does this work on Qt DEs as well (e.g. KDE) and if so, what do I need to have installed on the system?

**Comment by ilya-fedin** [comment]
> Does this work on Qt DEs as well (e.g. KDE) and if so, what do I need to have installed on the system?

I took the implementation from Engrampa, you could test with it.

**Comment by mikhailnov** [comment]
It's a great feature, thanks a lot!

**Comment by john-preston** [comment]
Thanks, that's cool.

**Pull request merged**
