### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by Macsch15**

### CODE REVIEW

**Comment by stek29** [comment]
All translations are maintained on transifex.
Also, I doubt TDesktop would add Polish translation as one of official until other apps do it.

**Comment by john-preston** [comment]
All translations are managed on transifex, sorry.

**Comment by dzek69** [comment]
@stek29 
> Also, I doubt TDesktop would add Polish translation as one of official until other apps do it.

What do you mean by "other apps"? Just another client like Telegram for Android for example or really "other app" like Whatsapp?

**Comment by stek29** [comment]
@dzek69 I've meant other official telegram apps.

For now you can use custom localization files, every official app except WP (and macOS swift?..) supports them.

About transifex -- sorry, I don't know.

**Comment by dzek69** [comment]
How to use custom localization files without recompiling whole app? My Linux version has just two binary files, my Windows version doesn't seem to hold translation files with the app

**Comment by stek29** [comment]
@dzek69 open settings, type "loadlang". File chooser will appear, chose your .strings file. Done.

**Comment by dzek69** [comment]
wow, hidden feature, thanks

**Pull request closed without merging**
