### PR TITLE
Clean up DESKTOP_APP_DISABLE_WEBRTC_INTEGRATION

### PR DESCRIPTION
**Pull request by mymedia2**
Either way, the feature is not working, and nobody seems to use it.

Link: https://github.com/desktop-app/lib_webrtc/pull/2
Link: https://github.com/desktop-app/cmake_helpers/pull/77
Closes: #8483

### CODE REVIEW

**Comment by john-preston** [comment]
@mymedia2 Please update https://github.com/desktop-app/lib_webrtc/pull/2 and I'll merge those.

**Comment by mymedia2** [comment]
@john-preston ok, done

**Comment by john-preston** [comment]
@mymedia2 🤔  Why did you remove lib_tgvoip and RegisterTagLegacy? Calls from new tdesktop versions to old versions on all systems work only through libtgvoip.

**Comment by mymedia2** [comment]
It looks like my mistake, sorry. I should put that line back.

**Comment by john-preston** [comment]
Thanks!

**Pull request merged**
