### PR TITLE
"..." instead of ".."

### PR DESCRIPTION
**Pull request by braska**

### CODE REVIEW

**Comment by ilyamodder** [comment]
+1

**Comment by auchri** [comment]
Whats about the ellipsis character? (... vs …)

**Comment by telegramdesktop** [comment]
We just like two dots, sorry ¯\_(ツ)_/¯

**Comment by dottorblaster** [comment]
Sorry for being a grammar nazi, but this PR should be implemented.

**Comment by julianxhokaxhiu** [comment]
Although I'm pro to this PR, it's really funny how this was closed :dancer: 

@telegramdesktop maybe you should re-consider it :)

**Comment by DaFri-Nochiterov** [comment]
`*1 april joke*`
Add checkbox to change dots count

**Comment by dottorblaster** [comment]
asd

**Comment by doublejumper** [comment]
But... Web version has 3 dots, what about consistency?

I tried. :c

**Pull request closed without merging**
