### PR TITLE
Get rid of redudant cmake options

### PR DESCRIPTION
**Pull request by ilya-fedin**

### CODE REVIEW

**Comment by john-preston** [comment]
Thanks!

**Comment by AndydeCleyre** [comment]
I usually build with `TDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME` -- can someone tell me why it's become redundant?

**Comment by ilya-fedin** [comment]
@AndydeCleyre there's no need to disable scheme registration anymore

**Comment by AndydeCleyre** [comment]
@ilya-fedin Thank you but can you elaborate a bit? You mean it will never try to do scheme registration?

**Comment by ilya-fedin** [comment]
> Thank you but can you elaborate a bit? You mean it will never try to do scheme registration?

it will, but it's ok. It won't introduce a second menu item.

**Comment by AndydeCleyre** [comment]
So if a user has a different app associated with `tg://` URIs, then installs this, this won't steal that association?

**Comment by ilya-fedin** [comment]
> So if a user has a different app associated with `tg://` URIs, then installs this, this won't steal that association?

It will.

**Comment by AndydeCleyre** [comment]
So how can we continue to prevent this app from doing that? On a linux system, AFAIU, all that should be needed is the 

```ini
MimeType=x-scheme-handler/tg;
```

line in the `.desktop` file, and anything further will be invasive and stepping on users' and admins' toes. In other words, the app itself should *advertise* its ability to deal with those URIs, not *choose for a user or system* that this is the best choice.

**Comment by ilya-fedin** [comment]
>  the app itself should _advertise_ its ability to deal with those URIs, not _choose for a user or system_ that this is the best choice

This behavior was chosen by @john-preston, if you don't like it, you should discuss with him about that. Personally, I think there should be a dialog like firefox has, but I guess preston won't be thrilled with this idea :)

**Comment by AndydeCleyre** [comment]
I thought the choice until this PR was to offer `TDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME` as a way to disable the invasive behavior. Is there an issue or other reference for the reversal of that choice?

**Comment by ilya-fedin** [comment]
> I thought the choice until this PR was to offer `TDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME` as a way to disable the invasive behavior.

As far as I know, it was there only due to the fact that it creates a second menu entry for packaged installation. Since it compatible with packaged build now, there no need for it anymore.

>  Is there an issue or other reference for the reversal of that choice?

No, this was discussed privately. The main reason was the fact that people installing tdesktop via package managers creating issues about the non-working handler. So, we decided to remove the flag and if some maintainer really want to remove handler installation, he should patch the source code and only he will be completely responsible for this choice.

**Comment by AndydeCleyre** [comment]
> The main reason was the fact that people installing tdesktop via package managers creating issues about the non-working handler.

Can you reference such an issue? I found:

- #2630 -- but that was a multiple-handler-entry issue
- #3674 -- but that's **not** using a package manager and is about firefox, **not** xdg
- #7305 -- but that's **not** using a package manager and the reporter went MIA
- #8626 -- never properly debugged, possibly a firefox issue, not enough info

So that last one, #8626, is the only one I could find matching your description. Are you saying "the main reason" for this change was that one bug report that was never thoroughly investigated? Or am I missing reports in my search?

**Comment by ilya-fedin** [comment]
> Are you saying "the main reason" for this change was that one bug report that was never thoroughly investigated?

Yeah, such issues appear from time to time and reporters just disappear usually, so we decided just to ensure that telegram is default, just like on other platforms.

Just like I said earlier, if you don't like the behavior, you should discuss that with preston, not with me.

**Comment by AndydeCleyre** [comment]
I cannot find a second issue as you describe. Are you *sure*

> such issues appear from time to time

?

As I said, I only found one such issue, and it was never thoroughly investigated.

> if you don't like the behavior, you should discuss that with preston, not with me.

I don't mean to target you, I just thought this was the most relevant place for the inquiry. 

Pinging @john-preston

**Comment by ilya-fedin** [comment]
> Are you _sure_

No, I'm not sure.

**Comment by ilya-fedin** [comment]
I understand that you just want the old behavior, but this issue is cross-platform, you could have multiple Telegram clients on Windows or macOS and tdesktop will overwrite your default. There is no reason that Linux should be handled differently.

**Comment by AndydeCleyre** [comment]
I cannot speak for the best ways to handle protocol assignment on those other platforms.

It seems to me that this new behavior removes the option for protocol assignment to be handled *correctly* on linux, not simply *differently*.

I have yet to see any evidence or explanation of the `TDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME` behavior being incorrect or inferior, while the opposite and newly mandatory behavior is demonstrably problematic in that it clobbers user preferences, requiring manual intervention on every update, and is in principle disrespectful to the user.

**Comment by ilya-fedin** [comment]
> while the opposite and newly mandatory behavior is demonstrably problematic in that it clobbers user preferences, requiring manual intervention on every update, and is in principle disrespectful to the user

This issue is not specific to Linux and should be addressed in a cross-platform manner.

**Comment by ilya-fedin** [comment]
> I have yet to see any evidence or explanation of the `TDESKTOP_DISABLE_REGISTER_CUSTOM_SCHEME` behavior being incorrect or inferior, while the opposite and newly mandatory behavior is demonstrably problematic in that it clobbers user preferences, requiring manual intervention on every update, and is in principle disrespectful to the user.

Well, I can say that this is just your opinion. There's another opinion: automatic default chaging is useful for who want just to start the app and use it. We can argue about that for long, but I tired of it and want to stop the discussion.

**Comment by AndydeCleyre** [comment]
The fact that it clobbers user preferences is not an opinion.

> automatic default chaging is useful for who want just to start the app and use it

But it's not been demonstrated that this actually solves an issue that is not already solved by the content of the `.desktop` file.

**Pull request merged**
