### PR TITLE
Fix build with GCC 12.

### PR DESCRIPTION
**Pull request by joecool1029**
I also did the same with lottie, let me know if it was correct way to approach this.

### CODE REVIEW

**Comment by john-preston** [comment]
I've merged the PR to lib_lottie, you can update the submodule in this PR.

**Comment by joecool1029** [comment]
Ok, the submodule has been updated in this.

**Comment by john-preston** [comment]
@joecool1029 Sorry, it looks like you've updated lib_lottie submodule to _your_ commit, that you've PR-ed to lib_lottie repository. But when I've merged it the commit has changed (so in the lib_lottie repository it is a different commit) and I want you to update submodule to the commit from the repository.

Your commit:

https://github.com/desktop-app/lib_lottie/commit/c99ff64fc4f08d5ff12b54cfcedef4b09322b4e5 (see the information above that it doesn't belong to any tree in the repository)

The real commit that appeared in the branch:

https://github.com/desktop-app/lib_lottie/commit/f3563bc6b0e042095d4d667d013f62cb8ae62b65

**Comment by joecool1029** [comment]
Apologies, I've corrected that now.

**Comment by john-preston** [comment]
Thanks!

**Pull request merged**
