### PR TITLE
Update Ubuntu support version

### PR DESCRIPTION
**Pull request by omkarnathsingh**

### CODE REVIEW

**Comment by john-preston** [comment]
I heard that Ubuntu 18.10 is awfully supported (I'd say not supported). It can thing for several minutes on launch eating 100% CPU.

**Comment by john-preston** [comment]
@omkarnathsingh Yes, but until the prebuilt binary (and not snap) is offered here:

https://desktop.telegram.org

I wouldn't say it is well supported :(

**Comment by 0xEAB** [comment]
Since 8ee958bfa08b2ba87cffaf8de4b65b6890e59ea3 fixed the main problem, is it possible to merge this now?

**Comment by Aokromes** [comment]
1.4.8 works fine, this pr can be merged :)

**Comment by stek29** [comment]
damn, I can't merge now because CI was triggered and it's currently broken :(

**Pull request merged**
