### PR TITLE
Get language name and country name from QLocale (Linux)

### PR DESCRIPTION
**Pull request by vitlav**

### CODE REVIEW

**Comment by john-preston** [comment]
@vitlav Platform::SystemCountry returns two-symbol country code, like US or UK, but QLocale::countryToString(locale.country()) returns UnitedStates.

**Comment by vitlav** [comment]
> @vitlav Platform::SystemCountry returns two-symbol country code, like US or UK, but QLocale::countryToString(locale.country()) returns UnitedStates.
Need we ISO 639-1 two-letter codes in that place?

**Comment by vitlav** [comment]
Well, if we need two-symbol code for a language name and two-symbol code for a country name, just split locale name (ru_RU, en_GB, en_US, el_GR) by lodash.

**Comment by john-preston** [comment]
Thanks.

**Pull request merged**
