### PR TITLE
Allow searching for messages by a user who has left a chat, fixes #5667

### LINKED ISSUE #5667: Can't search for messages of left users
### Steps to reproduce
1. User1 joins a group.
2. User1 posts some messages.
3. User1 leaves the group.
4. User2 clicks the search icon in the group.
5. User2 clicks the silhouette icon in the search field.

### Expected behaviour
All users that have posted non-deleted messages in the group are listed.

### Actual behaviour
Only current members of the group are listed.

### Configuration
**Operating system:** Debian GNU/Linux 10

**Version of Telegram Desktop:** 1.5.4

**Used theme**: Classic

### PR DESCRIPTION
**Pull request by udf**
This is PR #5728 but with a fix that allows searching for your own messages. Also [this request](https://github.com/telegramdesktop/tdesktop/pull/5728#pullrequestreview-212555077) has been done.

The original PR message from @TheWug follows:

-----

fixes #5667

Change `Dialog::SearchFromController` to inherit not from `ParticipantsBoxController`, which only shows the users in the group, but instead from `AddSpecialBoxController` which shows the group's users but falls back on global search as well.

I know you don't generally accept pull requests for features and calling this a bug is very borderline but I figured I'd post it anyway.

### CODE REVIEW

**Comment by john-preston** [comment]
Thanks!

**Comment by bodqhrohro** [comment]
Unfortunately, this resolves the issue only partially. It's still not possible to search for the messages of accounts who don't have a username and of deleted accounts.

**Comment by udf** [comment]
@bodqhrohro Not being able to search for accounts without a username is definitely a bug, does this happen regardless if the account is in the group?

As for deleted accounts, I'm not sure how this would be implemented. Allowing searching by ID would definitely work, however there's no easy way to get the ID of an account in tdesktop.

**Comment by Aokromes** [comment]
kotatogram shows id of user, so maybe someone can cherry pick the commit implementing it.

**Comment by bodqhrohro** [comment]
> @bodqhrohro Not being able to search for accounts without a username is definitely a bug, does this happen regardless if the account is in the group?

I re-checked: it works well with ordinary names, but fails on a name that consists only from an emoji.

Actually, I consider this implementation quirky: not only it's non-intuitive and still gives no clue what users have written in a group, but also brings all the flaws of the global search which is too fuzzy and excessive for this task. Still better than nothing, though, and thank you for that. Ideally, the list of writers instead of the list of participants should be displayed, but AFAIK, it's not implemented in Client API yet :/

**Pull request merged**
