### PR TITLE
Russian lang.

### PR DESCRIPTION
**Pull request by garex**
* Source files updated
* Built and tested to looks nice in most places
* Bad news: Russian lang has more complex plural rules
and "sexual" verb endings, that currently solved
as "сообщения(-ий)" or "сделал(-а)"
* It should be done in more nice way later

At https://www.transifex.com/projects/p/telegram-desktop/ 33 langs
requested, but no one accepted. After Russian will be there,
I can sent translation there too. Or it's could be extracted
from lang_ru.strings there by tx tool.

For translation thanks to Alla Ustimenko http://angloved.ru

### CODE REVIEW

**Comment by garex** [comment]
Rebased on latest master.

`tx push -s` to add to transifiex.

**Comment by petRUShka** [comment]
Waiting for translation request to be accepted!

**Comment by garex** [comment]
@petRUShka I think it's a anti-Russian sanctions here :)

**Comment by garex** [comment]
@telegramdesktop If you need — I can rebase it on latest master and check once again for untranslated strings (may be they are exists already).

**Comment by telegramdesktop** [comment]
Languages are not managed from here, sorry.

**Comment by garex** [comment]
@telegramdesktop when other langs will be here? https://www.transifex.com/telegram/telegram-desktop/

**Pull request closed without merging**
