### PR TITLE
fix do not using input method and adding the Chinese spuort

### PR DESCRIPTION
**Pull request by aphuse**
Fixed under Linux can't use the input method and added the Chinese language support.

### CODE REVIEW

**Comment by m13253** [comment]
It seems that only fcitx is fixed.

Is there any plan to support ibus? I need ibus to input Japanese and Chinese.

**Comment by aphuse** [comment]
The ibus is fixed too.


来自 MEIZU MX

-------- 原始邮件 --------
发件人：Star Brilliant <notifications@github.com>
时间：周六 5月30日 08:40
收件人：telegramdesktop/tdesktop <tdesktop@noreply.github.com>
抄送：aphuse <xiezhifu@gmail.com>
主题：Re: [tdesktop] fix do not using input method and adding the Chinese spuort (#759)

**Comment by m13253** [comment]
1. Why are you modifying `Readme` to replace "Official" to "No official" if you intended to make a pull request? (BTW the antonym of "official" is "unofficial" instead of "no official")

2. I think you'd better change the title to something that makes sense in English. I suggest "Fix CJK input method issue on Linux & add Chinese translation"

3. I do not think your Chinese translation is of good enough quality. Maybe it is better if we can work together to improve the translation, and submit it with a separate pull request.

---

Chinese version if you have difficulty reading the above:

1. 既然你打算发 Pull Request 了，为何要修改 `Readme` 中的“官方”为“没有官方”呢？（顺便，“官方 Official”的反义词是“非官方 unofficial”，而不是“没有官方 no official”）

2. 我觉得你最好把标题改成有意义的英语。我建议“修复 CJK 输入法问题 & 增加中文翻译 Fix CJK input method issue on Linux & add Chinese translation”

3. 我觉得中文翻译质量还不够好。或许我们可以一起改善翻译，然后作为另一个 Pull Request 来提交。

**Comment by aphuse** [comment]
貌似作者不响应他人的pull request，估计合不进去，这个pull request要撤了。我在archlinux用我那边的github代码打包，所以后面改了下Readme


来自 MEIZU MX

-------- 原始邮件 --------
发件人：Star Brilliant <notifications@github.com>
时间：周六 5月30日 13:03
收件人：telegramdesktop/tdesktop <tdesktop@noreply.github.com>
抄送：aphuse <xiezhifu@gmail.com>
主题：Re: [tdesktop] fix do not using input method and adding the Chinese spuort (#759)

**Comment by iven** [comment]
@aphuse 修 Bug 辛苦了。我觉得你最好能留一个专门分支用来跟上游提 PR，这样关了 PR 有点太可惜了。另外作者才两天没响应啊，给他点时间，毕竟在 #375 里面响应过的。

Better use a seperate branch to send pull requests and give the author some time to review and test.

**Comment by mxa** [comment]
this is a essential feature. please fix it.

**Comment by xxxifan** [comment]
+1

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

**Comment by m13253** [comment]
> Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

Thanks a lot!
I will test it and report later today.

**Comment by MingcongBai** [comment]
I am following up on this issue. I am using `ibus` under KDE Plasma Desktop 5. IME will not work when replying to a message.

**Comment by m13253** [comment]
> Please check out 0.8.50 dev version, it should be fine there, I've added Qt plugins for IBus and Fctix.

Positive test results from Gnome with ibus.
All textboxes are able to type.
However I haven't noticed the problem that was reported above by @MingcongBai .

**Comment by MingcongBai** [comment]
> However I haven't noticed the problem that was reported above by @MingcongBai .

No joke, I've just (sadly) find out that it is only reproducible when using `kwin` (or actually `kwin_x11`). When I right-click on a message, the window loses its focus (as per @m13253 has noticed), however when I clicked on "Reply", the window will not regain focus.

I've tested it under `mutter` (GNOME), and `openbox` and the window was able to regain focus, therefore I am able to type when trying to reply to someone.

Well, but it is usable currently. If you would click again on the window after clicking on "Reply" (which again, makes the window to lose focus), you will be able to work around this issue. Still annoying though. 

I will file a but to KDE.

**Comment by MingcongBai** [comment]
https://bugs.kde.org/show_bug.cgi?id=351382 a bug is filed to KDE as well.

**Pull request closed without merging**
