### PR TITLE
Commented Placeholders

### PR DESCRIPTION
**Pull request by SmartManoj**

### CODE REVIEW

**Comment by SmartManoj** [comment]
Add predefined labels for New Issue Template also

**Comment by SmartManoj** [comment]
Version of Telegram Desktop: 1.7.14
Add latest version automatically

**Comment by SmartManoj** [comment]
Use numeric list for ### Steps to reproduce

**Comment by SmartManoj** [comment]
https://raw.githubusercontent.com/SmartManoj/SmartUserScripts/master/Tdesktop_Issues.user.js

**Comment by john-preston** [comment]
There are conflicts.

**Pull request closed without merging**
