### PR TITLE
fixes #6410

### LINKED ISSUE #6410: [Bug] - See who is online straight from the chat list, not disappear until there is mouse movement
The connected user does not disappear until there is mouse movement above the user (I do not know if it only happens with users with thumbtacks)
Fallo 
Linux Mint 19.2 64bit XFCE

### PR DESCRIPTION
**Pull request by Optiligence**
the animation callback didn’t work before

### CODE REVIEW

**Comment by john-preston** [comment]
The animation shouldn't play if the row isn't visible on screen, it should switch the dot instantly.

I hope this issue is already fixed in 4.3 version.

**Comment by Optiligence** [comment]
i can add the visible toggle back; but i’m not a fan of seeing logic like this, Qt should be able to handle that

but i thought it’s not a good idea if the user scrolls it into view later on (and i wasn’t sure if it’s updated from somewhere else)
the 2 other places that call `updateCornerBadgeShown` don’t provide a proper callback, so they – as is – can’t start an animation

**Comment by Optiligence** [comment]
the issue persists with 4.3.0

**Comment by Optiligence** [comment]
also: 
>it should switch the dot instantly.

i don’t think that’s what the code does though
since the issue wasn’t that only the animation was missing – the dot remained…
(except if there is a repaint when comes into view)

**Comment by john-preston** [comment]
It should be fixed in the next version 4.3.1, I hope to release it today.

**Pull request closed without merging**
