### PR TITLE
 Update README.md with a new supported OS

### PR DESCRIPTION
**Pull request by rezasp**
Update README.md with a new supported OS

### CODE REVIEW

**Comment by john-preston** [comment]
Fedora 22 is not supported anymore? If it is, please change to 22 - 24, not just 24.

**Comment by rezasp** [comment]
Updated.
* Fedora 22 - Fedora 24

**Comment by auchri** [comment]
The signature is still missing.

**Comment by rezasp** [comment]
What is your mining about "signature" ?

**Comment by auchri** [comment]
See [CONTRIBUTION.md](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work).

**Comment by rezasp** [comment]
@auchri Thanks for replay , i changed commit description with sign.

**Pull request merged**
