### PR TITLE
Fix compile and linking ffmpeg_utility.cpp

### PR DESCRIPTION
**Pull request by perestoronin**

### CODE REVIEW

**Comment by john-preston** [comment]
This will crash.

**Comment by john-preston** [comment]
```
QPixelLayout qPixelLayouts[QImage::NImageFormats];
const auto layout = &qPixelLayouts[QImage::Format_ARGB32];
const auto convert = layout->storeFromARGB32PM;
...
convert(blabla)
```

You create an empty array of things and then try to call a method with address from that not-filled-with-anything array.

**Comment by xvitaly** [comment]
@john-preston Do not use Qt private API methods in your code!

**Comment by john-preston** [comment]
@xvitaly This is irrelevant to the fact that this PR can't be merged.

**Pull request closed without merging**
