### PR TITLE
Windows - Not showing notifications if currently in Full Screen mode …

### PR DESCRIPTION
**Pull request by karkason**
…(i.e. presentation or youtube video)

Resolves my #7611 issue :)

### CODE REVIEW

**Comment by ilya-fedin** [comment]
There are already SkipToast and SkipAudio methods

**Comment by john-preston** [comment]
@karkason But it is already done here:

https://github.com/telegramdesktop/tdesktop/blob/1e5aa2a78d0a0ba06d95c63e746d7b795fe838b8/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp#L714-L724

If you've checked your changes, can you check why they work differently from that is already there in SkipToast method?

**Comment by karkason** [comment]
> @karkason But it is already done here:
> 
> https://github.com/telegramdesktop/tdesktop/blob/1e5aa2a78d0a0ba06d95c63e746d7b795fe838b8/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp#L714-L724
> 
> If you've checked your changes, can you check why they work differently from that is already there in SkipToast method?

You’re right. I’ll look into it!

**Comment by john-preston** [comment]
Please reopen if there is new information.

**Pull request closed without merging**
