### PR TITLE
v1.9.2: Build fix

### PR DESCRIPTION
**Pull request by sina-ht**
Revert codegen to the commit without timestamp code.
Add new/removed source files to/from Telegram/gyp/telegram/sources.txt

Signed-off-by: Hiroshi Takekawa <sian.ht@gmail.com>

### CODE REVIEW

**Comment by john-preston** [comment]
Sorry, guys, this is not correct, I just need to update instructions to use CMake.

**Comment by sina-ht** [comment]
> Sorry, guys, this is not correct, I just need to update instructions to use CMake.

Thank you for your quick reply!

I just wanted developers to know some fixes are needed.
I'd appreciate if you understood the tagged commits should be build-able.

**Comment by john-preston** [comment]
@sina-ht Yeah, I see. They are buildable, but not like it is said in instructions 😭 You can try running "Telegram/configure" (.bat or .sh) and then build in "out" folder, if CMake runs successfully.

**Comment by sina-ht** [comment]
> @sina-ht Yeah, I see. They are buildable, but not like it is said in instructions  You can try running "Telegram/configure" (.bat or .sh) and then build in "out" folder, if CMake runs successfully.

Thank you again!  It's a great tip.

**Pull request closed without merging**
