### PR TITLE
Use linux icon theme

### PR DESCRIPTION
**Pull request by L0L022**
Put the icon file in .local/share/icons/ to let the user's theme get the upper hand (ex: default kde icons theme)

### CODE REVIEW

**Comment by auchri** [comment]
Hi, please squash your commits and add the "Signed-off-by" to your final commit.

**Comment by L0L022** [comment]
It worked ?

**Comment by auchri** [comment]
No, now you have 7 commits instead of one :)

For instructions, see http://stackoverflow.com/a/5201642

After that, you have to use `git push --force` to override the existing commits :)

**Comment by L0L022** [comment]
YES ! I missed the push --force :)

**Comment by bil-elmoussaoui** [comment]
+1 to merge this!

**Comment by auchri** [comment]
@bil-elmoussaoui yes, after the bugs in the current version ate fixed :)

**Pull request merged**
