### PR TITLE
test

### PR DESCRIPTION
**Pull request by auchri**

### CODE REVIEW

**Comment by auchri** [comment]
TEST

**Comment by auchri** [comment]
TEST

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See [travis build](https://travis-ci.org/telegramdesktop/tdesktop/jobs/))

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See [travis build](https://travis-ci.org/telegramdesktop/tdesktop/jobs/142011323))

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See [travis build](https://travis-ci.org/telegramdesktop/tdesktop/jobs/))

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See [travis build](https://travis-ci.org/telegramdesktop/tdesktop/jobs/))

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See [travis build](https://travis-ci.org/telegramdesktop/tdesktop/jobs/1111))

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See [travis build](https://travis-ci.org/telegramdesktop/tdesktop/jobs/142014508))

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See [travis build](https://travis-ci.org/telegramdesktop/tdesktop/jobs/142014935))

**Comment by stek29** [comment]
What?

**Comment by auchri** [comment]
:grinning:

**Comment by stek29** [comment]
Aha, testing API?

**Pull request closed without merging**
