### PR TITLE
Update message_field.cpp

### LINKED ISSUE #6794: Cannot create a hyperlink with IP address
## Steps to reproduce
1. Open "Create link" from context menu or Ctrl+K in message field
2. Try to create link with http://1.1.1.1/ or https://1.1.1.1/ as URL

### Expected behaviour
Hyperlink should be created, like in both default Android client and TGX, and can be sent in message,

### Actual behaviour
URL field is highlighted red, indicating that link is incorrect.

### Configuration
**Operating system:** Windows 10 x64
**Version of Telegram Desktop:** 1.9.1 beta

### PR DESCRIPTION
**Pull request by sa3eedDev**
fix the verification of url to support ip addresses. closes #6794

### CODE REVIEW

**Comment by Aokromes** [comment]
you can add #closes https://github.com/telegramdesktop/tdesktop/issues/6794 :) on that way the bug your PR is fixing will be automatically closed.

**Comment by sa3eedDev** [comment]
#closes #6794

**Comment by Aokromes** [comment]
it looks you closed this pr by mistake xd reopen it and edit 1st post to put the closes #6794 thing :)

**Comment by sa3eedDev** [comment]
I don't understand why it failed in appveyor it should be fine

**Comment by john-preston** [comment]
This is not a fix for verification, it is just removing of the verification.

**Comment by john-preston** [comment]
If this type of URL works for server (it leaves it clickable) then please add a valid verification, not just allow any text in the URL field.

**Pull request closed without merging**
