### PR TITLE
Create lang_zh_Hans.strings

### PR DESCRIPTION
**Pull request by fangliye**

### CODE REVIEW

**Comment by dongfengweixiao** [comment]
中文语言包，在你之前已经有多人提交（包括我）但是并不去合并。。。

**Comment by telegramdesktop** [comment]
Languages are not managed from here, sorry.

**Comment by MingcongBai** [comment]
@telegramdesktop If I may ask, where is the place that those data are "managed" in?

**Comment by auchri** [comment]
https://www.transifex.com/telegram/telegram-desktop/langstrings/

**Pull request closed without merging**
