### PR TITLE
Do not depend on MFC

### PR DESCRIPTION
**Pull request by OZ1**
Telegram.rc depends on afxres.h. This file is installed with MFC. For the project to compile it is sufficient to use winres.h
https://connect.microsoft.com/VisualStudio/feedback/details/759972/rc-files-include-mfc-headers-even-when-mfc-is-not-installed

### CODE REVIEW

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

**Comment by OZ1** [comment]
guess it's done

**Comment by auchri** [comment]
Hi, please resolve the conflicts

**Comment by OZ1** [comment]
merged in updated master

**Comment by auchri** [comment]
thanks!

**Pull request merged**
