### PR TITLE
Add "Copy name" option (Requested in #1783) (2)

### PR DESCRIPTION
**Pull request by stek29**
Also add `lng_profile_copy_fullname` to lang.strings

I've broken my repo, so github haven't updated previous request

### CODE REVIEW

**Comment by stek29** [comment]
Some screenshots:
Name only: 
Name only
Name and username: 
Name and Username
Name and Number: 
Name and Number
Name, Number and Username: 
Name, Number and Username


Also when `last_name` is empty it copies `First `, not `First`, but it's `lng_full_name` issue.

**Comment by auchri** [comment]
The "Signed-off-by:" [signature](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) is now missing :/

**Comment by stek29** [comment]
@auchri Done :)

**Comment by john-preston** [comment]
Thanks!

**Pull request merged**
