### PR TITLE
Don't clear undo history when applying draft

### LINKED ISSUE #2963: Deleted previous messages while we are typing.
Deleted previous messages while we are typing.

### Steps to reproduce
1. go to a private chat with a user
2. try to type text
3. In the box type a message. When I am typing. Just accidental. Previous sometimes typed messages Is cleared.

### Configuration
**Operating system:** GNU/LINUX , Ubuntu 16.10
also some my friend have this problem.

**Version of Telegram Desktop:** 1.0.5 ( is lastest version)

### PR DESCRIPTION
**Pull request by stek29**
Kinda fixes #2963, #2315, #2371.

### CODE REVIEW

**Comment by stek29** [comment]
Huh, Travis check failed because it wasn't able to clone Qt sources :D
Maybe #3200 was a good idea?

**Comment by auchri** [comment]
@stek29 It worked after I restarted the job, maybe code.qt.io had an issue.

**Comment by stek29** [comment]
@auchri that's what @grasmanek94 said in #3552 -- git was unavailable for him, but https worked.

**Comment by john-preston** [comment]
@stek29 Can you please verify that the undo history is still cleared when you switch between chats? (perhaps the changes to field content is done by the same draft methods).

Switching between chats should clear the undo history, otherwise you can switch to a chat, press Undo and get a message prepared for a completely different chat!

**Comment by stek29** [comment]
@john-preston It doesn't :(

**Comment by stek29** [comment]
@john-preston Should be fine now

**Comment by john-preston** [comment]
Yes, looks fine now. Thanks!

**Pull request merged**
