### PR TITLE
Add 15 min to autolock box isssue #6640

### PR DESCRIPTION
**Pull request by edrisranjbar**
as @BrainNull requested in issue #6640; I added this feature.
please check it and if it is ok, Merge this.

### CODE REVIEW

**Comment by 23rd** [comment]
I don't think that's a good idea.

We can add this "15 minutes" item, but what if someone else opens a new issue and wants to add another time?
In my opinion, this problem should be solved by replacing radio button with time picker.
Anyway, I don't make the final decision.

**Comment by BrainNull** [comment]
Timepicker is the best solution

**Comment by edrisranjbar** [comment]
> I don't think that's a good idea.
> 
> We can add this "15 minutes" item, but what if someone else opens a new issue and wants to add another time?
> In my opinion, this problem should be solved by replacing radio button with time picker.
> Anyway, I don't make the final decision.

yes, I agree with time picker too.
if it is good, I can make it.

**Comment by mymedia2** [comment]
Solution with a time picker or a combo box is more difficult to implement since an internal lib_ui has no suitable widget.

**Comment by Aokromes** [comment]
1m/2m/5m/15m/30m
1h/2h/3h/6h/12h/24h better imho

**Comment by edrisranjbar** [comment]
> 1m/2m/5m/15m/30m
> 1h/2h/3h/6h/12h/24h better imho

This will be a long list of options; I think for UI this wont be good enough.
Can we just add a few items?

**Comment by john-preston** [comment]
No, this way the next guy will come around and ask for 10 minutes. Even the original linked issue #6640 asks for 30 minutes as well.

It could be done with a slider similar to one in Settings > Advanced > Manage local storage:

image

with a lot of values, like @Aokromes suggests (we need to keep old 5h there I think), something like:

1/2/5/10/15/20/30 minutes, 1/2/3/4/5/6/9/12/18/24 hours.

**Pull request closed without merging**
