### PR TITLE
Use message date by default when saving a photo (#1586)

### PR DESCRIPTION
**Pull request by Lonami**

### CODE REVIEW

**Comment by auchri** [comment]
@Lonami To get this PR merged, you have to fix the tests.

**Comment by Lonami** [comment]
> you have to fix the tests.

I'm not sure what really failed though? I checked the logs and couldn't find anything relevant. The change is so small I don't understand why that one build failed.

**Comment by john-preston** [comment]
@Lonami click on "Details" link and you'll see the appveyor build log. It has warning (that is treated as an error):

"c:\tbuild\tdesktop\telegram\sourcefiles\mediaview.cpp(788): warning C4003: not enough actual parameters for macro 'qsl'"

because of a "qsl()" expression. For an empty string you should use "QString()" instead.

**Comment by Lonami** [comment]
> because of a "qsl()" expression. For an empty string you should use "QString()" instead.

I see now, that's what I thought which could be the reason. Thank you both! I'll fix it tomorrow and `git commit` a squash.

**Comment by Aokromes** [comment]
@Lonami you don't need to squash anymore, now github allows to squash on merge :)
(unless it's TC contribution requirement)

**Comment by Lonami** [comment]
> now github allows to squash on merge

I know, I often use it, but I forgot to add the "Signed off" thing to the commit message, so I simply `squash`'ed the commits to keep the original message.

**Pull request merged**
