### PR TITLE
Deep Link for Opening Profile, Like Android

### PR DESCRIPTION
**Pull request by ArmeF97**
This PR aims to follow @M299792458 advice to make a PR based on https://github.com/TDesktop-x64 fork, cherry-picking the commits.

See #8825

### CODE REVIEW

**Comment by john-preston** [comment]
I don't really like the idea of "openmessage" handler. How can it be used? How can you know any valid id of a message in users inbox? Only user knows ids of his messages, this is not a channel, where everyone has the same messages.

**Comment by john-preston** [comment]
Also, those `userId = stringValue("user_id").toInt()` + `static_cast<PeerId>(userId)` won't work anymore. You need something like `userId = UserId(stringValue("user_id").toULongLong())` + `PeerId(userId)`.

**Comment by john-preston** [comment]
This "user" link is a strange thing as well. This link will work or won't work depending on the fact that user saw such user in current launch session or not. How can it be used reliably?

**Comment by ArmelliniFederico** [comment]
I don't have answers for your question because I simply cherrypicked the commits from a working fork (telegramx64). 
Maybe those commits will help you to implement this feature in your way and close #8825

**Comment by ArmeF97** [comment]
@john-preston 
I don't have answers for your question because I simply cherrypicked the commits from a working fork (telegramx64). 
Maybe those commits will help you to implement this feature in your way and close #8825

**Comment by john-preston** [comment]
Well, I don't see a use case for such links, that sometimes work and sometimes do not. In the official client there is no way to get a user id, so why would you like to support links by user id that sometimes work and sometimes do not - I don't know.

There is no problem in implementing something like that. There is a problem with explanation of why this will bring any real value to the users.

**Comment by ArmeF97** [comment]
@john-preston 
The reason why is explained in #8825 and it's simply the following: it's true that telegram desktop client won't show user id, but other clients can. On android links like tg://user?id=xxxx works so I see no reason why not make it work also on tdesktop. Official android client can do it so the main reason here is simply consistency between mobile and desktop

**Comment by john-preston** [comment]
Yes, they work there, but there is no explanation why would you like them.

Also, they won't work well on tdesktop, because when you launch tdesktop you have no information about any users at all, so if you click on such link it will or won't work depending on did you or did you not see this user (in a group or in chats list) in this exact session.

This is unreliable so I was wondering why would anyone want such unreliable feature before implementing it. A link to a specific message is even a more strange feature. You can't know any valid message id in someone else inbox, and you have no way of getting a message id or user id in any of the official apps (if I remember correctly).

**Comment by ArmeF97** [comment]
@john-preston 
Well, now that I understood what you are referring to, I think you are right. It would have been simply something "more" than something less, but if you see no value in it, it's your call. Close also #8825 then

**Comment by bb010g** [comment]
@john-preston

> Also, they won't work well on tdesktop, because when you launch tdesktop you have no information about any users at all, so if you click on such link it will or won't work depending on did you or did you not see this user (in a group or in chats list) in this exact session.

tdesktop could query the UID if necessary when resolving a `tg:user?id=${UID}` URL? Linking directly off of UIDs is useful for when you want to refer to a specific account robustly over username changes, or when you want to store a link to a Telegram user that doesn't have a username outside of Telegram, for use in Telegram at a later date.

> You can't know any valid message id in someone else inbox, and you have no way of getting a message id or user id in any of the official apps (if I remember correctly).

Your own user ID at least can be trivially retrieved through the official Bot API. (I think Telegram clients should allow for opting-in to viewing IDs, like Discord clients when Developer Mode is enabled, but that's another matter.)

**Comment by john-preston** [comment]
@bb010g No, tdesktop (or any other Telegram app) can't query users by ID only, Telegram API simply doesn't give you user by his ID, only by his ID and a 64 bit access hash, that is different for different users. You get this access hash when server gives you the user somewhere (in your chats list, or contacts list, or some group members list).

**Pull request closed without merging**
