### PR TITLE
Close a race between Gio threads and Qt application init.

### PR DESCRIPTION
**Pull request by glebius**
QApplication has a historical feature[1] of calling setlocale(3) at init,
which today cause more harm than good.  Such call isn't thread safe neither
per C standard, not per any known libc implementation.  The Gio threads
would call into locale reading functions all the time, so early access to
locale by Gio may race with setlocale() by Qt leading to undefined behavior.

Platform specific start before the Sandbox (aka QApplication) is at core
design of tdesktop and that order can't be changed. There is no way to pause
Gio until QApplication instantiates.

Fortunately, Qt library itself has a static global flag that prevents it
from calling setlocale() twice. We don't even need to instantiate a
temporary QCoreApplication, we can just call into the method.  So call
it right before launching Gio.

[1] https://chat.stackoverflow.com/rooms/63812/discussion-between-phil-armstrong-and-matteo-italia

### CODE REVIEW

**Comment by ilya-fedin** [comment]
I don't like having such a call in IsIBusPortalPresent, it feels like a hack. IsIBusPortalPresent can be moved to other place and that call will become useless.

**Comment by john-preston** [comment]
@glebius Thank you very much for this research.

@ilya-fedin We have calls to `Glib::init` and `Gio::init` in `Platform::Launcher::exec`. As the docs state "Gio::init() calls Glib::init(), which sets the global locale as specified by Glib::set_init_to_users_preferred_locale()". (maybe we should leave only `Gio::init` call then?)

I suggest placing the `QCoreApplicationPrivate::initLocale();` call there with a link to #16922. I'm not sure if it should go before `Gio::init` or after (this will result in one or another locale call being made last). I think it can go before, that way it surely won't race with gio code even if it decides to spawn threads and do some other strange things right in `init` call.

**Comment by ilya-fedin** [comment]
> maybe we should leave only `Gio::init` call then?

https://github.com/GNOME/glibmm/blob/master/glib/glibmm/init.cc#L41-L46

**Comment by ilya-fedin** [comment]
> I suggest placing the `QCoreApplicationPrivate::initLocale();` call there with a link to #16922. I'm not sure if it should go before `Gio::init` or after (this will result in one or another locale call being made last). I think it can go before, that way it surely won't race with gio code even if it decides to spawn threads and do some other strange things right in `init` call.

`init` call is a glibmm's (C++ wrapper's) thing, I don't think it will start threads. IMHO, the right place for `QCoreApplicationPrivate::initLocale();`  is in Platform::start, right after mallctl call

**Comment by john-preston** [comment]
@ilya-fedin Ok, let it be `Platform::start` then.

**Review by john-preston — CHANGES_REQUESTED** [review]
> IMHO, the right place for QCoreApplicationPrivate::initLocale(); is in Platform::start, right after mallctl call.

**Comment by ilya-fedin** [comment]
https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdbusprivate.c#L317-331
изображение

**Comment by ilya-fedin** [comment]
Since dbus connection object is being destroyed when leaving IsIBusPortalPresent, I would expect the thread to be destoryed as well. But they don't destroy it.

**Comment by glebius** [comment]
Thanks! Will update request in a few minutes.

P.S.
> Since dbus connection object is being destroyed when leaving IsIBusPortalPresent, I would expect the thread to be destoryed as well. But they don't destroy it.

Even if they destroyed them, the race would still be there.

**Comment by ilya-fedin** [comment]
> Even if they destroyed them, the race would still be there.

How it can be there if there would be no thread that doing that?

**Comment by ilya-fedin** [comment]
Also, you should target dev branch, not master branch

**Comment by glebius** [comment]
> How can it be there if there would be no thread doing that?

You are right, that if that code wasn't commented out, the race would not exist. The code actually doesn't destroy threads, the threads cease themself. The commented code waits for them to complete their operation, basically removing any parallelism after gio object is destroyed. Note that g_thread_join() is commented out twice :)

**Comment by glebius** [comment]
> Also, you should target dev branch, not master branch

Thanks, will do!

**Comment by glebius** [comment]
I failed to change target branch for the GitHub pull request, so looks like I need to create a new one. Sorry for that.

**Comment by ilya-fedin** [comment]
You can change target branch, but you can't change source branch. One of the reasons it's a good idea to create a custom branch for PR.

**Pull request closed without merging**
