### PR TITLE
Fix dir separator on windows

### PR DESCRIPTION
**Pull request by XiangQingW**
Fix dir separator on windows

### CODE REVIEW

**Comment by XiangQingW** [comment]
The %LIBS_DIR%\\Qt-5.15.2 dir doesn't been generated after running `tdesktop\Telegram\build\prepare\win.bat`.

**Comment by 23rd** [comment]
Maybe it would be better to use `dirSep` instead.

**Comment by XiangQingW** [comment]
@23rd I have just replaced it with `dirSep`, please review again.

**Comment by john-preston** [comment]
I wonder how this fixes anything. There is code later that still uses the universal separator:
```
if not os.path.isdir(libsDir + '/' + keysLoc):
    pathlib.Path(libsDir + '/' + keysLoc).mkdir(parents=True, exist_ok=True)
```
I'm afraid the problem may be somewhere else, in the build qt / install qt steps.

**Comment by ilya-fedin** [comment]
btw, there's os.path.join in python

**Comment by john-preston** [comment]
Ok, I don't really understand, how this fixes anything, but the change looks benign.

**Pull request merged**
