### PR TITLE
Remove unnecessary memory allocations in localstorage

### PR DESCRIPTION
**Pull request by MihaZupan**

### CODE REVIEW

**Comment by john-preston** [comment]
@MihaZupan Are you sure it is unnecessary? When you write a QByteArray into a stream you don't write only the content itself (audio.size()), but also some meta information, like the size of the buffer and maybe something else.

**Comment by MihaZupan** [comment]
My bad, only 1 quint32 is not needed. QDataStream prepends a quint32 for length with byte arrays and strings. In writeWebFile, one such prefix is already accounted for when calling stringsize.

**Comment by john-preston** [comment]
@MihaZupan Then perhaps it should just use "Serialize::bytearraySize" there instead of this manual counting.

**Comment by MihaZupan** [comment]
Updated it to use "Serialize::bytearraySize" and found a couple more instances of an extra quint32

**Pull request closed without merging**
