### PR TITLE
Add MPRIS support

### LINKED ISSUE #9961: [Feature Request] Media control using MPRIS
### Is your feature request related to a problem?
Telegram Desktop is last music player which can't be controller using MPRIS-compatible media player interface on Linux.
Even firefox allows to be controlled by that.
This would allow DE to show playing track, rewind, skip and pause playback.
Also would make possible to control music playback on KDE connect and another similar tools.

### Describe the solution you'd like
Implement MPRIS DBus API

### Describe alternatives you've considered
I don't really know any alternatives, MPRIS is gold standard on linux, supported on Gnome, KDE and other DEs.

### Additional context
Would allow eg. to control music playback with this KDE widget:
Screenshot_20201220_123110
Or from phone on KDE connect:
image

### PR DESCRIPTION
**Pull request by ilya-fedin**
Closes #9961

### CODE REVIEW

**Comment by john-preston** [comment]
Wow, thanks.

**Comment by TheWeirdDev** [comment]
This is what I have been waiting for, for a long time. Thank you!

**Comment by JuniorJPDJ** [comment]
Wow! Thanks! Now we need new release and I'll be pleased <3

**Comment by ilya-fedin** [comment]
> Wow! Thanks! Now we need new release and I'll be pleased <3

it's already in release, starting from 2.7

**Pull request merged**
