### PR TITLE
Make Telegram Windows Controls more Native Looking

### PR DESCRIPTION
**Pull request by onenachi**
Windows Users unfortunately don't get a native titlebar. Instead they get a small titlebar with non windows like window buttons.

This commit basically makes the titlebar controls and titlebar size more like a native Windows 8+ program for windows users by changing the titlebar dimensions and adding titlebar window button assets that look nearly identical to the Windows 10 ones.

image

### CODE REVIEW

**Comment by onenachi** [comment]
Referencing this relevant issue:

https://github.com/telegramdesktop/tdesktop/issues/2818

**Comment by john-preston** [comment]
That's interesting. I think if we want to replicate the default Windows 10 top bar we need to check if the rendering is pixel-perfect in both regular window and maximized window (the title height and buttons sizes are different in maximized window for the native Windows 10 windows).

**Comment by onenachi** [comment]
>           That's interesting. I think if we want to replicate the default Windows 10 top bar we need to check if the rendering is pixel-perfect in both regular window and maximized window (the title height and buttons sizes are different in maximized window for the native Windows 10 windows).

Unfortunately I don't know how to do maximized window sizes in QT. If you can give me an icon size, I can however make the icons for it.

**Comment by onenachi** [comment]
>           That's interesting. I think if we want to replicate the default Windows 10 top bar we need to check if the rendering is pixel-perfect in both regular window and maximized window (the title height and buttons sizes are different in maximized window for the native Windows 10 windows).

Actually @john-preston the maximized window titlebar size in Windows 10 UWP applications is the same as when not maximized (tested for OneNote, Edge, Windows 10 Mail, the Windows 10 Store...).

**Comment by john-preston** [comment]
@onenachi It doesn't change for Edge and other UWP apps I guess. But it does change for native apps, like File Explorer or mspaint (I guess you name that Old Windows Styling):

image

image

It makes sense for Edge, because it has tabs inside the title bar, but I don't see any sense for such thick bar in maximized tdesktop.

**Comment by john-preston** [comment]
I see buttons 92x56 (I think it's 2x, so they're 46x28), maximized 92x44 (so 46x22). But this is Parallels on a Mac, so maybe your dimensions (46x30, 46x23) are more accurate.

**Comment by john-preston** [comment]
So, in my system it doesn't exactly fit (top one native, bottom one tdesktop from this PR):

image

Native bar has less height and the icons are a bit less as well (this is 2x: 2x20, 20x20, 20x20).

**Comment by onenachi** [comment]
> @onenachi It doesn't change for Edge and other UWP apps I guess. But it does change for native apps, like File Explorer or mspaint (I guess you name that Old Windows Styling):
> 
> image
> 
> image
> 
> It makes sense for Edge, because it has tabs inside the title bar, but I don't see any sense for such thick bar in maximized tdesktop.

Edge and UWP apps are native Apps. So are Visual Studio and so on. The apps you are talking about such as the Windows explorer are legacy Win32 applications that MS hasn't got around to rebuilding in the modern framework (Settings will eventually fully replace control panel and so on).

Obviously the easiest test for this is to develop a basic winforms/wpf application in dotnet core 3 since they were newly launched and see how they will scale. I will try that and post screenshots.

**Comment by onenachi** [comment]
> So, in my system it doesn't exactly fit (top one native, bottom one tdesktop from this PR):
> 
> image
> 
> Native bar has less height and the icons are a bit less as well (this is 2x: 2x20, 20x20, 20x20).

Looking at some native and nonnative apps:

- Slack and other WinRT apps (windows 8) have 30px tall menubars maximized and 31px tall menubars restored plus a 1px border.
- UWP/Modern apps have 32px tall menubars maximized and 32px tall menubars restored plus a 1px border
- Legacy apps have a 23px tall menubar maximized and a 30px tall menubar restored plus a 1 px border
- Modern WPF and Windows Forms applications also render like legacy applications, which is even more confusing.

**Comment by onenachi** [comment]
> So, in my system it doesn't exactly fit (top one native, bottom one tdesktop from this PR):
> 
> image
> 
> Native bar has less height and the icons are a bit less as well (this is 2x: 2x20, 20x20, 20x20).

The dimensions I have used is
                     (padding 10)
(padding 18) icon 10x10 (padding 18)
                     (padding 10)

So at 100% scaling they seem fine for me. I'll look into the scaling.

**Comment by onenachi** [comment]
@john-preston check out my latest pull. It should be pixel perfect with the legacy style of things.

What is remaining:
- Well I cant seem to figure out how to do the 1px border in QT. The border must also disappear when maximized.

image

screenshot 16

**Comment by john-preston** [comment]
@onenachi No border for now, I was not going to add it.

**Comment by 23rd** [comment]
I think this is not good idea, to make title bar "more Native Looking".
If you want it to look native, you need to consider drawing the title on all supported Windows systems, not only Win 10.
And even so, you spent a lot of time to perfectly fit the height pixels. But this PR does not take into account whether user has changed size of text in the title bar, which leads to a change in height of this title bar.

For example, on the value of the 8 title bar will be smaller, on the value of 12 - bigger.

I think the current title bar looks like it should.

image

**Comment by onenachi** [comment]
@23rd IMO the problem with the current titlebar is it's simply too small. Especially if you happen to have a touch device which the rest of Windows 10 was designed for. And it looks out of place on Windows vs the Mac and Linux applications which look native. The Mac app is also a custom titlebar themed to look like Mac.

In addition, while I do agree that titlebar font doesn't respect Windows font scaling, titlebar size does respect Windows scaling as it did prior, and that's the major Windows scaling. It's a step up from the current titlebar.

I do agree that maybe going fully native with the titlebar and themeing that may be a better option, but as John said, coloring that perfectly to match telegrams theme is hard if not impossible.

**Comment by Gordon01** [comment]
+1 for native window titlebar

**Comment by grishka** [comment]
> coloring that perfectly to match telegrams theme is hard if not impossible

It is kinda possible by going deep into how Windows draws windows. For example, handling the `WM_NCPAINT` message allows apps to draw whatever they want over the native window border/titlebar. But then you can probably still use the custom title bar but scale it to match the system-defined height which [you can obtain programmatically](https://stackoverflow.com/questions/21566307/how-to-get-the-title-bar-height-and-width-for-aero-and-basic-design).

**Comment by Yash-Garg** [comment]
Great idea of native titlebar 👍

**Comment by yassine-ah** [comment]
The current one is too small, let get this one even if it is not 100% perfect
After having it, we can start talking about details and create new issues to improve it 😄

**Comment by ArmeF97** [comment]
I don't think it's tiny. I'd make it even smaller, if it were to me. If you are going to add this, please at least let the users keep the small one, by a setting option

**Comment by rezaei** [comment]
[Feature Request] grouping channels and groups and chats separately [make diffrent attributes such as color or category] #6420
 —— we need to have the ability to manage and categorize groups and channels and chats, because there are many channels and groups and chats that make me confuse and also make telegram unhelpful, I think its better for me if I can add these elements in the desired categorize with desired names like 'education' 'industry' 'family' 'friends' 'colleagues' 'sport' and so on ...

**Comment by kcohar** [comment]
I think this is a great idea because the current title bar is too small and the only apps that I use that seem to have this problem are Telegram and Discord. This would make Telegram's title bar more like WhatsApp's and bring it up to snuff.

Does this patch work with the night/dark version too?

**Comment by Aokromes** [comment]
Conflicting files
Telegram/SourceFiles/platform/win/window_title_win.cpp
Telegram/SourceFiles/window/window.style

**Comment by Aokromes** [comment]
@onenachi

**Comment by ilya-fedin** [comment]
Maybe it's better to get the buttons via winapi? Like Chrome & Firefox does
Then rendering will be pixel-perfect :thinking:

**Comment by noobj2** [comment]
I think if they used native title bars now, it would look weird. i don't know if i want native title bars for telegram desktop after all these years of using non-native ones.
but yea, current title bar is too small, i would love to have a bigger title bar. same as it is, just a bit bigger.

**Comment by tooomm** [comment]
I assume this is superseded with the fix of #2958 now?

**Comment by john-preston** [comment]
yup

**Pull request closed without merging**
