### PR TITLE
Add official Russian and Ukrainian localizations

### PR DESCRIPTION
**Pull request by ezdev128**
Hello,
I'd like you to review this pull-request.
Thanks!

### CODE REVIEW

**Comment by telegramdesktop** [comment]
Languages are not managed from here, sorry.

**Comment by BANOnotIT** [comment]
@ghost, where can people add localisations to telegram?

**Comment by stek29** [comment]
@BANOnotIT on Transifex.

**Comment by BANOnotIT** [comment]
@stek29 there's no russian language in plans. I can't propose russian on transifex...

**Comment by stek29** [comment]
@BANOnotIT ¯\_(ツ)_/¯

**Pull request closed without merging**
