### PR TITLE
Added '-name' command-line argument for custom Qt application name.

### LINKED ISSUE #6951: [Feature Request] Add -class option to set WM_CLASS
### Is your feature request related to a problem?
I use multiple telegram accounts and in ubuntu gnome, they're grouped in the dock by WM_CLASS of the telegram and because of that grouping accessing them by clicking in the dock is difficult 

### Describe the solution you'd like
I would like to have -class option so I add it to my .desktop file to set the WM_CLASS at startup

### PR DESCRIPTION
**Pull request by XamarinDeveloper**
Will set WM_CLASS option in some desktop environments.
Fixes #6951

### CODE REVIEW

**Comment by john-preston** [comment]
Is the app custom built in those environments? Maybe it should be done in the build time?

**Comment by XamarinDeveloper** [comment]
> Is the app custom built in those environments? Maybe it should be done in the build time?

No, it's for the runtime you can see the details in the related issue

> There's no need in such argument, you can set custom class name via RESOURCE_NAME environment variable.

Wow, thanks, I did not know that and this really should've been said in the issue thread, anyway there still is the need of -class option to set the RESOURCE_NAME environment variable at runtime. I've written a shell file for it but it's not very convenient.

If I do that, will it be approved? or there is no way this option is gonna be implemented?

**Comment by ilya-fedin** [comment]
> anyway there still is the need of -class option to set the RESOURCE_NAME environment variable at runtime.

Why just not toadd the variable to a .desktop file?

**Comment by XamarinDeveloper** [comment]
> Why just not toadd the variable to a .desktop file?

I still need to learn a lot :man_facepalming:
I'll close the issue as well, Thank you so much

**Pull request closed without merging**
