### PR TITLE
Remove unneeded tabs

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by Aokromes** [comment]
This pull request contains merge conflicts that must be resolved.

Maybe this PR is no longer needed?

**Comment by jubalh** [comment]
hehe :-)
This PR is from July, so I bet there are merge conflicts now :-)
However you guys still have many trailing whitespaces. You can close this PR and I will file another okay?

**Comment by jubalh** [comment]
Check this out: https://github.com/telegramdesktop/tdesktop/pull/464

**Comment by jubalh** [comment]
@Aokromes dont forget to pull it in before it gets outdated again :-)

**Pull request closed without merging**
