### PR TITLE
Remove rounded rectangle style

### PR DESCRIPTION
**Pull request by wbsdty331**

### CODE REVIEW

**Comment by auchri** [comment]
Signature is missing 😉

**Comment by wbsdty331** [comment]
@auchri
But maybe that's not the point.
I don't like rounded rectangle style, and I think other people have had the same idea like me.

This is it.

**Comment by auchri** [comment]
I know, but the signature is still missing.

**Comment by wbsdty331** [comment]
what signature?
GPG?

**Comment by auchri** [comment]
Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See travis build)

**Pull request closed without merging**
