### PR TITLE
data: List compatible form-factors

### PR DESCRIPTION
**Pull request by Kekun**
This will allow the app to be available in Phosh and PureOS Store.

### CODE REVIEW

**Comment by ilya-fedin** [comment]
I'm not sure this is valid since tdesktop doesn't aim to adapt for smartphones

**Comment by Nirzak** [comment]
> I'm not sure this is valid since tdesktop doesn't aim to adapt for smartphones
> 
> Not to say that tdesktop minimal width and height are too big for these form-factors, like been reported by #8058
> 
> So, this won't correspond to reality. But you still could PR this only with "Workstation" and it will be fine I think

Yeah, I agree with that. It should only for workstations or tablets, not mobile devices. As such small screen is not feasible for tdesktop.

**Comment by ilya-fedin** [comment]
@john-preston maybe close this? :thinking:

**Review by kinglyonais — APPROVED** [review]

**Comment by john-preston** [comment]
@Kekun Are you sure it works fine and fits on mobile devices that allow to install apps from those "Phosh and PureOS Store"? If not, please remove mobile compatibility mentioning, if yes, I'll merge without changes.

**Comment by ilya-fedin** [comment]
#8058, #8810 and #10193 definitely show that it's not

**Comment by ilya-fedin** [comment]
why no-response doesn't close that :hmm:

**Comment by john-preston** [comment]
😞

**Pull request closed without merging**
