### PR TITLE
include cmake/varaibles.cmake only after project() is called

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by john-preston** [comment]
@maxice8 I'm afraid this is not possible, because mac os deployment target should be specified before the project is called.

**Comment by maxice8** [comment]
can the build_linux32 be moved to somewhere else that can be called after ? use CMAKE_SIZEOF_VOID_P is the best option.

Or we can match CMAKE_SYSTEM_PROCESSOR and hope we don't get false positives + update whenever new arches appear.

**Comment by john-preston** [comment]
And right now what works wrong? Maybe just match "64" in `uname -m`? Or it doesn't work already somewhere?

**Comment by john-preston** [comment]
Ok, I'll do it your way.

**Pull request closed without merging**
