### PR TITLE
WinGet: Publish beta releases also

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
@john-preston @ilya-fedin this PR adds beta releases too.

### CODE REVIEW

**Comment by ilya-fedin** [comment]
I have no merge rights, sorry

**Comment by vedantmgoyal2009** [comment]
cc @john-preston

**Comment by vedantmgoyal2009** [comment]
@john-preston Once final last thing. Please add `workflow` scope to the token. 

Reference: https://github.com/telegramdesktop/tdesktop/actions/runs/3070963617/jobs/4961218190#step:2:720

**Comment by john-preston** [comment]
@vedantmgoyal2009 oh, it gives full control of repositories.. this is really needed? why does creating PRs need this access?

**Comment by vedantmgoyal2009** [comment]
GitHub doesn't allow to push the branch to remote (telegramdesktop/winget-pkgs). You can see the logs for more info.

PR creation only needs `public_ repo` scope.

**Comment by ilya-fedin** [comment]
Do you push binary package to git repo? Why do you do that?

**Comment by vedantmgoyal2009** [comment]
There the winget manifests, not the binaries.

**Comment by ilya-fedin** [comment]
ah

**Comment by john-preston** [comment]
@vedantmgoyal2009 It works now?

**Comment by vedantmgoyal2009** [comment]
Yes 🎉

**Pull request merged**
