### PR TITLE
Add more emoij shortcuts

### PR DESCRIPTION
**Pull request by bobvdvalk**
Add emoij shortcuts like the old msn and Skype.

### CODE REVIEW

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See travis build)

**Comment by bobvdvalk** [comment]
I added the sign off message :)

**Comment by stek29** [comment]
Please, *don't replace* `:)`, `;)`, `:D` and `:(`!

**Comment by miladeleven** [comment]
the best way to do this would be a customized emoji shortcut. every one can have their own shortcut! and we can edit it.-

**Comment by MaTiNBLaCk1** [comment]
Hi
Can You Make Short Code For All Emoji like Poker Face emoji " :| "?
http://uupload.ir/files/zp63_capture.png

**Comment by bobvdvalk** [comment]
Well I want to but my skills in C++ are not good enough to do that..

**Comment by MaTiNBLaCk1** [comment]
Hi    Thank you to answer me
if your skills in C++ are not good enough to do that 
Why do you introduce yourself as a professional programmer? :|

**Comment by bobvdvalk** [comment]
Wow.. Thanks for you nice comment....

First of all I wasn't responding to you but to **miladeleven**.
And second, I mostly program in Java so I am not famiar with C++.

But thanks for you nice comment.

**Comment by MaTiNBLaCk1** [comment]
I'm really sorry because I think the answer Comment

**Comment by bobvdvalk** [comment]
Is there something going to happen with this pr? Or do I need to change something? It's not very clear to me.

**Comment by Lazek** [comment]
+ Please applied this changes.

**Comment by thomasbiesaart** [comment]
Can we merge this?

**Comment by zaps166** [comment]
This patch doesn't work for me (compiled with telegram v0.10.7, why?) :cry:

Btw. ":)" can have other emoji than ":-)"

**Comment by nop144d** [comment]
Doesn't work for me too. Telegram Desktop v0.10.11

**Comment by stek29** [comment]
Then it may be closed 😀

**Pull request closed without merging**
