### PR TITLE
A little French translation

### PR DESCRIPTION
**Pull request by Super-Baleine**
Hey,
I've done a partial French translation.

I'll finish it later. :)

### CODE REVIEW

**Comment by Aokromes** [comment]
idk if it also needs fr.lproj :)

**Comment by Super-Baleine** [comment]
@Aokromes  ?

**Comment by stek29** [comment]
Translations are maintained on Transifex

**Comment by Aokromes** [comment]
@Super-Baleine if you notice other locales contains a directory called fr.lproj

**Pull request closed without merging**
