### PR TITLE
Use XDG Desktop Portal for file dialog

### PR DESCRIPTION
**Pull request by ilya-fedin**
See also: https://github.com/desktop-app/cmake_helpers/pull/17
Should help with https://github.com/telegramdesktop/tdesktop/issues/2411

### CODE REVIEW

**Comment by john-preston** [comment]
Thanks!

**Comment by grulja** [comment]
Why do you use the portal directly? It will be used automatically when you use QFileDialog.

**Comment by grulja** [comment]
I'm not sure this is needed. Qt will automatically use XdgDesktopPortal platform theme when Flatpak or SNAP is detected.

**Comment by ilya-fedin** [comment]
This is not for snap/flatpak

**Pull request merged**
