### PR TITLE
Telegram: Add flash window option.

### PR DESCRIPTION
**Pull request by angelsl**
Add option to enable/disable window flashing.
untitled

### CODE REVIEW

**Comment by Aokromes** [comment]
This pull request contains merge conflicts that must be resolved.

**Comment by angelsl** [comment]
@Aokromes: So if I fix them, will this PR be merged?

Because I submitted this 2 months ago, and in that time I got frustrated with compiling my own version with this commit _every goddamn time_ a new version was released because apparently the project owner doesn't accept any pull requests, and just moved to Telegram Web.

**Comment by Aokromes** [comment]
Dunno :) but if you fix it you will have higher probability of being merged :)

**Comment by programcoder** [comment]
What does Flash window do exactly?

**Comment by telegramdesktop** [comment]
Perhaps such feature will be added after Settings redesign, when notification settings will be separated from other and the whole section won't be such a mess.

I've added [new contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md), so it is clearly stated now, that no features will be accepted in format of pull requests, only bug fixes and code improvements.

**Comment by angelsl** [comment]
It's almost a year since I submitted this ...

**Pull request closed without merging**
