### PR TITLE
Add nimf inputcontext plugin for linux version

### PR DESCRIPTION
**Pull request by 5HARK**
Add nimf support(#2603)

nimf Qt IM Plugin Repo(for this PR): https://github.com/5HARK/im-nimf-qt5
Nimf Project Repo: https://gitlab.com/nimf-i18n/nimf

### CODE REVIEW

**Comment by john-preston** [comment]
I'm not sure I can merge that, because it adds a lot of new runtime dependencies. New shared library dependencies include:
```
libgio-2.0.so.0
libgobject-2.0.so.0
libgmodule-2.0.so.0
libz.so.1
libselinux.so.1
libresolv.so.2
libffi.so.6
```
That means that anyone without any of that libraries who will autoupdate Telegram Desktop will just get it not launching at all while working fine before the update.

**Comment by john-preston** [comment]
After trying to get rid of those new dependencies I understood that the problem lies deeper.

I load either gtk3 or gtk2 depending on the appindicator library I was able to load. Then I resolve all the used gtk methods from the loaded shared library dynamically (like g_free, g_[signal_smth] etc). I'm afraid that this nimf plugin that is linked to gtk2 specifically will work unreliably if I load and use gtk3 myself and then use gtk2 in this plugin. Also it just wont work if gtk is absent.

To do that the right way I need a way to suggest my dynamically resolved gtk functions to the plugin and for plugin to work with them or just return false in check() if the functions were not loaded. This can be hacked inside the nimf plugin code, but I didn't yet figure out how to do that in a nice way. Some header sharing is required between nimf plugin and tdesktop code.

**Comment by 5HARK** [comment]
The same glib will be loaded if gtk2 and gtk3 are installed on your system. It does not affect nimf plugin.

If you have only gtk2 installed on your system, you can not install Nimf. isValid() returns false.

Therefore, I think there is no problem. Is there anything else to consider?

**Comment by john-preston** [comment]
@5HARK Currently it brings new static dependencies. It should load the methods dynamically, otherwise I'm not sure that the app will continue working on the same systems it works right now.

**Comment by 5HARK** [comment]
@5HARK okay. i got it.
I will change im_nimf_qt5.cpp code for delete new static dependencies(glib, gio etc.)
and after that I will rewrite pull request again.

**Comment by 5HARK** [comment]
I updated nimf Qt IM Plugin Repo(for this PR): https://github.com/5HARK/im-nimf-qt5
Please review this PR again.

**Comment by john-preston** [comment]
Ok, I'll try to build it with the new plugin code.

**Comment by john-preston** [comment]
It builds fine and doesn't add new dependencies. I hope there won't be any weird runtime problems after such update.

**Comment by stek29** [comment]
> It builds fine

https://travis-ci.org/telegramdesktop/tdesktop/jobs/464207607#L4244 :(

**Pull request merged**
