### PR TITLE
add fcitx support

### PR DESCRIPTION
**Pull request by jqs7**
fix up fcitx not working in telegram on linux

### CODE REVIEW

**Comment by telegramdesktop** [comment]
Working on that right now, I think I could manage to build it in Ubuntu 12.

**Comment by jqs7** [comment]
@telegramdesktop  :+1:  :100:

**Comment by telegramdesktop** [comment]
Please check out 0.8.50 dev version, it should be fine there.

**Comment by jqs7** [comment]
@telegramdesktop works great ! thanks :+1:

**Pull request closed without merging**
