### PR TITLE
Fix applying of patches in Dockerfile.

### PR DESCRIPTION
**Pull request by mahdi-jfri**
The original command failed for me. Tried it out and the original given path was wrong. This commit fixes those patches.

### CODE REVIEW

**Comment by ilya-fedin** [comment]
This fix is wrong

**Comment by ilya-fedin** [comment]
The right fix is to add `WORKDIR ..` after `git checkout` in patches section

**Comment by mahdi-jfri** [comment]
you're right. fixed it

**Comment by ilya-fedin** [comment]
'of libproxy and glibmm' part is no longer valid in commit message, you're fixing this for all the patches

**Comment by mahdi-jfri** [comment]
Nice catch. Fixed that too.

**Comment by john-preston** [comment]
Thanks!

**Pull request merged**
