### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by Sea-n**
The following are commits related to removed variables.

Please let me know if there is something wrong.

## Removed variables

[apiwrap.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/apiwrap.cpp)
e050e27: `kSaveDraftBeforeQuitTimeout`

[app.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/app.cpp)
113f665: `serviceImageCacheSize`

[boxes/auto_download_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/auto_download_box.cpp)
a0c6104: `checked(Source source, Type type)`

[boxes/background_preview_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/background_preview_box.cpp)
b6edf45: `resultBytesPerPixel`
fe21b5a: `ms`

[boxes/calendar_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/calendar_box.cpp)
ae97704: `yearIndex`, `monthIndex`
99bb093: `ms`

[boxes/connection_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/connection_box.cpp)
f794d8d: `ping`

[boxes/dictionaries_manager.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/dictionaries_manager.cpp)
8353867: `session`

[boxes/peer_list_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/peer_list_box.cpp)
2ce2a14: `grayedWidth`

[boxes/peers/add_participants_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/peers/add_participants_box.cpp)
07e010d: `chat`, `channel`

[boxes/self_destruction_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/self_destruction_box.cpp)
fe9f02e: `count`

[chat_helpers/emoji_suggestions_widget.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/chat_helpers/emoji_suggestions_widget.cpp)
a12bc60: `is(QLatin1String string)`

[chat_helpers/field_autocomplete.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/chat_helpers/field_autocomplete.cpp)
8c7a35c: `atwidth`, `hashwidth`

[chat_helpers/gifs_list_widget.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/chat_helpers/gifs_list_widget.cpp)
ff65734: `inlineItems`
3d846fc: `newSelected`
d1687ab: `kSaveDraftBeforeQuitTimeout`

[chat_helpers/stickers_dice_pack.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/chat_helpers/stickers_dice_pack.cpp)
c83e297: `kZeroDiceDocumentId`

[chat_helpers/stickers_emoji_pack.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/chat_helpers/stickers_emoji_pack.cpp)
d298953: `length`

[chat_helpers/stickers_list_widget.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/chat_helpers/stickers_list_widget.cpp)
eb75859: `index`, `x`

[core/crash_reports.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/core/crash_reports.cpp)
5940ae6: `LaunchedDateTimeStr`, `LaunchedBinaryName`
~~f25e63b: `CrashLogged`~~

[data/data_changes.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_changes.cpp)
3c4e959: `clearRealtime`

[data/data_cloud_file.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_cloud_file.cpp)
4b354b0: `fromCloud`, `cacheTag`

[data/data_document_media.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_document_media.cpp)
7db5359: `kMaxVideoFrameArea`

[data/data_messages.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_messages.cpp)
794e315: `wasCount`

[data/data_photo_media.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_photo_media.cpp)
e27d2bc: `index`

[data/data_wall_paper.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_wall_paper.cpp)
b6edf45: `resultBytesPerPixel`

[data/data_types.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_types.cpp)
aa8f62d: `kWebDocumentCacheTag`, `kStorageCacheMask`

[history/admin_log/history_admin_log_inner.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/admin_log/history_admin_log_inner.cpp)
794e315: `canDelete`, `canForward`

[history/history_location_manager.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/history_location_manager.cpp)
60f45ab: `kCoordPrecision`
9f90d3a: `kMaxHttpRedirects`

[history/history_message.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/history_message.cpp)
cedf8a6: `kPinnedMessageTextLimit`

[history/history_widget.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/history_widget.cpp)
b305924: `serviceColor`
efa5fc4: `hasForward`
5e7aa4f: `kTabbedSelectorToggleTooltipTimeoutMs`, `kTabbedSelectorToggleTooltipCount`

[history/view/history_view_context_menu.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/view/history_view_context_menu.cpp)
fe1a90b: `isVideoLink`, `isVoiceLink`, `isAudioLink`

[settings.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/settings.cpp)
e2f54eb: `defaultRecent`

[settings/settings_folders.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/settings/settings_folders.cpp)
e8bf5bb: `kRefreshSuggestedTimeout`

[ui/filter_icon_panel.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/ui/filter_icon_panel.cpp)
c4a0bc1: `kDelayedHideTimeoutMs`

[window/themes/window_theme_preview.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/window/themes/window_theme_preview.cpp)
ef927c8: `mutedCounter`

## Modified variables

[boxes/stickers_box.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/boxes/stickers_box.cpp)
554eb3a: `_rows[pressedIndex]` -> `set`

[data/data_notify_settings.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/data/data_notify_settings.cpp)
734c410: `muteForSeconds` -> `muteUntil`

[history/view/history_view_list_widget.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/view/history_view_list_widget.cpp)
07528be: `_items[index]` -> `view`
e5f3bed: `fromState`, `tillState`

[history/history.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/history/history.cpp)
cd3c1c6: `kStatusShowClientsideRecordVideo` -> `kStatusShowClientsideRecordVoice`

[storage/download_manager_mtproto.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/storage/download_manager_mtproto.cpp)
ae8fb14: `_queues[dcId]` -> `queue`

[storage/localstorage.cpp](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/storage/localstorage.cpp)
357caf8: `MTP::Environment::Production` -> `production`

### CODE REVIEW

**Comment by john-preston** [comment]
@Sea-n How is CrashLogged not used? 🤔

**Comment by Sea-n** [comment]
@john-preston I didn't find any code related to `CrashLogged`, could you please point out where did it use? 🙇 

```cpp
bool CrashLogged = false;
[...]
{
    if (CrashLogged) return success;
        CrashLogged = true;
[...]
```

I think it's an always false condition, maybe I missed something.

**Comment by john-preston** [comment]
@Sea-n You wrote it here yourself 🙄

This guards the function to be called only once. If you remove the check it will be called any number of times.

**Comment by Sea-n** [comment]
Oh, my bad.

I didn't notice that code is inside the `DumpCallback()` function. 😅

**Comment by john-preston** [comment]
@Sea-n now I'm a bit scared, tbh 😅  I'll need to carefully look through the changes.

**Comment by Sea-n** [comment]
Sure, you can review it when you have time, this PR is not urgent.

Though the remaining part of change should be lead to compile error if I do wrong, it's better to take it carefully. 😊

**Comment by john-preston** [comment]
Thanks!

**Pull request merged**
