### PR TITLE
Create lang_vi.strings

### PR DESCRIPTION
**Pull request by meesudzu**
Add Vietnamese

### CODE REVIEW

**Comment by stek29** [comment]
Sorry, translations aren't accepted here. Wait for translations.telegram.org

**Comment by meesudzu** [comment]
Sory, I can't find vietnamese on that website, so i think i can contribute here.

**Comment by auchri** [comment]
Quote from https://translations.telegram.org/:

> If your language is not available yet, please wait – we will soon expand the interface to allow adding new languages.

**Comment by stek29** [comment]
@meesudzu That's why I suggested to wait. Sorry, I can't do anything about it. More languages should be added soon (tm).

**Comment by meesudzu** [comment]
Thanks, i'll test this translation while i wait The Telegram Team add Vietnamese to translation project.

**Pull request closed without merging**
