### PR TITLE
Changed to open audio stream on demand, rather than keeping it permanently open

### PR DESCRIPTION
**Pull request by brynthomas**
**Why:**

Keeping an audio stream open on Windows 8.1 prevents Windows from entering sleep.
Depending on the audio driver it can significantly increase CPU usage, in the form of AUDIODG.EXE on Windows or pulseaudio on Linux.
Depending on the audio driver it can force Windows to use high Timer Resolution, further draining battery.
(I sometimes have Telegram running in a Windows VM on my Mac, and having Telegram open and idle would use an extra 16% of a core. With this change it uses a negligible amount.)

**Addresses the following issues:**

telegramdesktop/tdesktop#229
telegramdesktop/tdesktop#258
telegramdesktop/tdesktop#351
telegramdesktop/tdesktop#176
telegramdesktop/tdesktop#191
telegramdesktop/tdesktop#179

**What changed:**

Split the audio initialisation (audioInit()) into separate methods:

1. Basic OpenAL setup was moved into AudioControl::setupCoreAL()
2. Loading the notification sound's WAV data was moved into AudioControl::loadNotificationWaveData()
3. Setting up the OpenAL buffers to play the notification sound was moved into AudioControl::setupNotificationAL()

This was split so that the notification sound's WAV data could be loaded once, even if the OpenAL specific commands needed to be rerun each time the audio stream was shut down and recreated.

Added a method AudioControl::audioRequired() that is called when the Notification Sound or a Voice Message is played, that resets up the audio stream if it has been shut down. It also resets the audio stream shutdown timer.

Added a timer method which gets executed after a few seconds of inactivity, and if no audio is playing (paused Voice Messages are still counted as playing), it will free buffers, sources, the audio context, and then close the device.

**Known implementation issue:**

If a Voice Message is paused in playback the audio stream will not shut down so as to maintain the context and position of playback. When you finish listening to the Voice Message, then the audio stream will shut down as normal.

Tested on Windows 8.1, Windows XP and Ubuntu 14.04

### CODE REVIEW

**Comment by telegramdesktop** [comment]
I've tried to fix that by pausing audio thread in Windows mmdevapi audio backend, check out 0.7.7 version. It should handle paused voice messages as well.

**Comment by ChrisCA** [comment]
I've tested 0.7.7 and it works correctly for me now.

**Comment by halega** [comment]
Can you fix it for Linux too? PulseAudio uses 8-9% of the CPU permanently + Telegram 2-3% = 10-12% CPU when idle. It's really annoying when you work on a notebook: fans always on.

Telegram 0.7.7
Fedora 21 Workstation
Linux 3.17.8-300.fc21.x86_64
pulseaudio 5.0-25.fc21

**Comment by brynthomas** [comment]
@telegramdesktop Great stuff, I see it's all working nicely on Windows now and with pauses. Hadn't really seen too much success from other people trying to get OpenAL to play nicely with suspension (think somebody had tried to get it to work with Blender that had a similar issue).

I suppose I was a little hesitant with doing a patch for a dependency like OpenAL just because it's one more thing to look after when updating to a newer version of OpenAL.

Was there a problem with the other backends (say Pulseaudio) and suspension so that the SuspendAndProcessSupported was restricted to Windows/MMDEVAPI?

**Comment by telegramdesktop** [comment]
>Was there a problem with the other backends (say Pulseaudio) and suspension so that the SuspendAndProcessSupported was restricted to Windows/MMDEVAPI?

I've just didn't check that, because in mmdevapi I've made "Suspend" just with a "Stop" call and "Process" just with "Start" call, and I'm afraid different backends could be not ready for such an approach :)

Seems like I should check for pulseaudio as well, because it gives some problems to the users. I've made only mmdevapi because it was the only case where users had the problem.

**Comment by vitaminace33** [comment]
@telegramdesktop I hope you can use this to solve #176.

**Comment by auchri** [comment]
I think @telegramdesktop fixed that, thankt you @brynthomas for the PR :)

**Pull request closed without merging**
