### PR TITLE
Read environment variables properly.

### PR DESCRIPTION
**Pull request by BOOtak**

### CODE REVIEW

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/.github/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.

(See travis build)

**Comment by BOOtak** [comment]
@auchri fixed, sorry for that

**Comment by auchri** [comment]
@BOOtak this breaks building like `qmake QT_TDESKTOP_PATH=${srcdir}/qt QT_TDESKTOP_VERSION=${_qtver} CONFIG+=debug "../../Telegram/Telegram.pro"`

**Comment by BOOtak** [comment]
@auchri Can I take a look at build logs?

**Comment by auchri** [comment]
@BOOtak sure: https://travis-ci.org/telegramdesktop/tdesktop/jobs/142189363

**Comment by BOOtak** [comment]
@auchri I see problem now. I thought QT_TDESKTOP_PATH and QT_TDESKTOP_VESION are environment variables and they were set incorrectly in .pro file. But according to travis build.sh they are actually qmake variables and they should be leaved as they are. If only you don't want to modify build.sh and replace this

```shell
qmake QT_TDESKTOP_PATH=${srcdir}/qt QT_TDESKTOP_VERSION=${_qtver} CONFIG+=debug "../../../../Telegram/build/qmake/codegen_style/codegen_style.pro"
qmake QT_TDESKTOP_PATH=${srcdir}/qt QT_TDESKTOP_VERSION=${_qtver} CONFIG+=debug "../../../../Telegram/build/qmake/codegen_numbers/codegen_numbers.pro"
qmake QT_TDESKTOP_PATH=${srcdir}/qt QT_TDESKTOP_VERSION=${_qtver} CONFIG+=debug "../../Telegram/MetaLang.pro"
```

with this:

```shell
QT_TDESKTOP_PATH=${srcdir}/qt
QT_TDESKTOP_VERSION=${_qtver}

qmake CONFIG+=debug "../../../../Telegram/build/qmake/codegen_style/codegen_style.pro"
qmake CONFIG+=debug "../../../../Telegram/build/qmake/codegen_numbers/codegen_numbers.pro"
qmake CONFIG+=debug "../../Telegram/MetaLang.pro"
```

__OR!__ We can combine those methods to read property from env variable __and__ from qmake variable. This won't require any updates of fragile build.sh and will allow me and other user configure build by env variables. What do you think?

**Comment by auchri** [comment]
> OR! We can combine those methods to read property from env variable and from qmake variable. This won't require any updates of fragile build.sh and will allow me and other users configure build by env variables. What do you think?

I think that's the best solution for everyone :+1:

**Comment by BOOtak** [comment]
@auchri should I do that in this PR or create new one?

**Comment by auchri** [comment]
Please create a new one :)

**Pull request merged**
