### PR TITLE
Improvements in Updater (win32)

### PR DESCRIPTION
**Pull request by QtRoS**
Few places in Updater code for Win32 were inaccurate (mostly related to usage UNICODE/ANSI versions of macroses/functions).

### CODE REVIEW

**Comment by telegramdesktop** [comment]
I've added [new contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md), so you'll need to make a pull request with the new "Signed-off-by:" signature in the commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) section.

**Comment by QtRoS** [comment]
Created new one: https://github.com/telegramdesktop/tdesktop/pull/1154

**Comment by telegramdesktop** [comment]
@QtRoS Yeah, thanks. But (for the future pull requests): there is no need to copy text of certificate of origin to the conversation :) and the commit message should be descriptive itself (something like "Improvements in Updater", and the signed-off-by line after this description).

**Comment by QtRoS** [comment]
Thanks! Now it's pretty clear - next time I'll do it right :)

**Pull request closed without merging**
