### PR TITLE
Updated genemoji to support short version smilies

### PR DESCRIPTION
**Pull request by bjaskj**

### CODE REVIEW

**Comment by drasive** [comment]
Nice, I wanted to do the same thing

**Comment by nmat** [comment]
+1

**Comment by joshery420** [comment]
Looks like at least a partial (not sure it covers 100% of cases) answer to issue #307 
Thanks @bjaskj!

**Comment by joshery420** [comment]
@bjaskj Curious, is there a specific reason why you didn't add short versions for things like 8-) and B-)?

**Comment by bjaskj** [comment]
I added those that I missed. Sorry if I overlooked something others use and miss :)

**Comment by rastersoft** [comment]
Please, please, please!!!!!! Merge this ASAP!!!!!!!

**Comment by ADTC** [comment]
@telegramdesktop And we're not merging this yet because.... ?

@bjaskj Thanks for this! Very nice. Regarding the 8-) and B-) (etc etc) you can add them and make a second commit to the same branch. It will automatically add to this pull request.

**Comment by telegramdesktop** [comment]
Perhaps some day this replacement array will be configured by user, but right now it is exactly the way it meant to be. I personally use :) and don't want it to be converted automatically and use "xD" and do want it to be converted. Sorry, but that stays the way it is.

I've added [new contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md), so it is clearly stated now, that no features will be accepted in format of pull requests, only bug fixes and code improvements.

**Comment by drasive** [comment]
The first point is subjective and I understand if you prefer to not have short versions of smileys,
but I personally feel a bit disappointed about not accepting any features from the community. I would imagine that some features of the desktop client wouldn't necessarily have a strong impact on the Telegram project as a whole.

**Comment by ADTC** [comment]
Frankly, your response is very disappointing. We all have preferences, likes and dislikes. We only ask that you provide to us the ability to configure and customize as per each of our preferences but you shot us all down with a response that you will dictate and enforce your personal preference on everyone else.

I hope you will reconsider. At the very least, a setting to enable or disable short smiley conversion would be adequate.

**Comment by telegramdesktop** [comment]
@drasive some times features can be accepted - when they do not conflict at all with our view of the desired progress. But it is so unpredictable from the side point of view, that much often case will be disappointment from declining of already prepared pull request with new features.

@ADTC I don't say that there won't be customization of emoji replacements ever, I say that they won't be changed in this pull request format.

**Pull request closed without merging**
