### PR TITLE
Add item to system tray to toggle notifications display

### PR DESCRIPTION
**Pull request by kirill-gerasimenko**
Hi,

I've added menu item to system tray context menu which toggles Display Notification setting.

notifications

Hope it might be helpfull!

### CODE REVIEW

**Comment by ScorpionIT** [comment]
good feature, merge please

**Comment by nmat** [comment]
+1

**Comment by telegramdesktop** [comment]
I've added [new contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md), so it is clearly stated now, that no features will be accepted in format of pull requests, only bug fixes and code improvements.

But exactly here perhaps an exception can be done :) if such pull request will be done without conflicts and with "Signed-off-by:" line in the commit message (see the [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) part) I will merge that.

**Comment by kirill-gerasimenko** [comment]
Hi,

I'll get it working with the latest sources in master and sign it as you suggested, thanks for feedback!

**Comment by auchri** [comment]
@kirill-gerasimenko Nice to hear, thank you! :+1:

**Comment by kirill-gerasimenko** [comment]
I've merged with latest from master and tested. I think it can be merged now.

**Comment by telegramdesktop** [comment]
@kirill-gerasimenko That one seems fine. I'll merge and test as soon as I get to it. Thanks.

**Comment by kirill-gerasimenko** [comment]
Thank you!

**Comment by telegramdesktop** [comment]
I've added some fixes.

**Comment by kirill-gerasimenko** [comment]
Thanks! Can't wait to see it in next version :)

**Comment by telegramdesktop** [comment]
@kirill-gerasimenko It is already available in the last decade version, you can download it from the bottom of https://desktop.telegram.org/#dev-version page.

**Comment by kirill-gerasimenko** [comment]
I'll give it a try, thanks!

**Pull request merged**
