### PR TITLE
[Feature Implementation] - Change notification sound (.wav, etc)

### PR DESCRIPTION
**Pull request by kireledan**
In response to issue #586 , I have implemented this feature.

### CODE REVIEW

**Comment by kireledan** [comment]
@telegramdesktop do you even look at these pull requests...?

**Comment by squirrelboot** [comment]
Yeah what's up with this? I've been waiting to see it implemented.. and I have yet to download a version over the last like.. 10.. that do not have this function yet.

**Comment by navjotjsingh** [comment]
@kireledan Why have you closed this pull request? This feature needs to be in the official app. @telegramdesktop Please look into this. This is a good feature to have.

**Comment by kireledan** [comment]
I closed this because It's in another PR

**Pull request closed without merging**
