### PR TITLE
Fix #3943 - Added note about loading v140 tools for VS 2017 required to build opus

### LINKED ISSUE #3943: Window build for opus fails missing v140 build tools (doc issue)
### Steps to reproduce
Building for windows per instructions

### Expected behaviour
Build should succeed

### Actual behaviour
opus release build fails

The instructions mention VS 2017, but the opus build needs the v140 build tools from VS 2015
These can be installed via the 2017 installer.

### PR DESCRIPTION
**Pull request by sjames1958gm**
Added note about loading v140 tools for VS 2017 required to build opus to the

### CODE REVIEW

**Comment by sjames1958gm** [comment]
My first PR - I feel I didn't do it correctly - I tried to squash commits, but I don't think I succeeded.

**Comment by stek29** [comment]
@sjames1958gm Yup, you didn't :c 
[There's a nice gist on squash I googled just now](https://gist.github.com/patik/b8a9dc5cd356f9f6f980)
But I'd just recreate PR if you want to do it via github site.
Just open the file in TDesktop repo (in repo you don't own), edit it, and then make a PR. github should do everything for you.

**Comment by auchri** [comment]
You don't have to squash your commits since github can do this 😊

**Comment by john-preston** [comment]
@auchri It won't be needed after the next update, because the opus build will use the v141 build toolset.

**Pull request closed without merging**
