### PR TITLE
Make theme preview fully translatable

### PR DESCRIPTION
**Pull request by RadRussianRus**
This PR makes theme preview fully translatable, like in other official clients.

## Tests

Custom Russian-based locale (all new keys translated):

Official Russian-based locale (no new keys):

English:

### CODE REVIEW

**Comment by john-preston** [comment]
@RadRussianRus This is not thread safe :( Theme preview is generated from a random background thread and it will crash if in that moment some langpack updates will happen, for example if an update with new langpack values will come from server.

**Comment by RadRussianRus** [comment]
Hmm, interesting. But some values are already translated. Are they thread safe?

**Comment by john-preston** [comment]
@RadRussianRus Like which ones?

**Comment by RadRussianRus** [comment]
These two:


First is from `Generator::paintDialogs`, [line 575](https://github.com/telegramdesktop/tdesktop/blob/04b9d4bdb5a660fc35b1457cd5ec125784f135d0/Telegram/SourceFiles/window/themes/window_theme_preview.cpp#L575):
```c++
_p->drawText(phRect, tr::lng_dlg_filter(tr::now), QTextOption(st::dialogsFilter.phAlign));
```

And second is from `Generator::paintComposeArea`, [line 539](https://github.com/telegramdesktop/tdesktop/blob/04b9d4bdb5a660fc35b1457cd5ec125784f135d0/Telegram/SourceFiles/window/themes/window_theme_preview.cpp#L539):
```c++
_p->drawText(placeholderRect, tr::lng_message_ph(tr::now), QTextOption(st::historyComposeField.placeholderAlign));
```

**Comment by john-preston** [comment]
@RadRussianRus No, that’s bad too :(

**Comment by RadRussianRus** [comment]
I guess they should be hardcoded then. Alright, guess I'm closing this pull for now. Thank you!

**Comment by john-preston** [comment]
@RadRussianRus No, it could be done right. They should be collected on the main thread and then passed down to the generator.

**Pull request closed without merging**
