### PR TITLE
Workaround internal compiler error in GCC

### PR DESCRIPTION
**Pull request by mymedia2**
Small fix for build with GCC 8.2.0

### CODE REVIEW

**Comment by Aokromes** [comment]
you can add closes #5111 on description and it will close ticket on merge :)

**Comment by mymedia2** [comment]
@Aokromes, this is not the only keyword that allows to close issues via 
commit message. GitHub also supports "fixes". See 
https://help.github.com/articles/closing-issues-using-keywords/

@john-preston, the patch has been updated.

**Comment by john-preston** [comment]
Thanks.

**Comment by mymedia2** [comment]
oops, I accidentally mixed up target branches, and the patch got into the master branch :disappointed_relieved:

**Pull request merged**
