### PR TITLE
Multiple language fixes

### PR DESCRIPTION
**Pull request by mathifonseca**
I added one more dot to the ellipses in English and improved some grammar. Also, made some other improvements in Spanish and Portuguese texts.

### CODE REVIEW

**Comment by auchri** [comment]
Hi,
thanks for the pull request!

Please read our [contributing policy](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md). You'll need to make a pull request with the "Signed-off-by:" signature being the last line of your commit message, like it is described in [sign your work](https://github.com/telegramdesktop/tdesktop/blob/master/CONTRIBUTING.md#sign-your-work) section. That will grant your work into the public domain.
Also squash your commits to a single commit.

**Comment by telegramdesktop** [comment]
@mathifonseca I'll look into English changes, but other languages are not changed via git, they are edited on transifex. Thanks anyway.

**Comment by mathifonseca** [comment]
Hi @auchri, my bad! I have to admit that I didn't read the policy :( I'm very sorry! 
@telegramdesktop, do you want to close this PR so I create a new one only with English changes? Also, can I have access to the Transifex project?

**Comment by john-preston** [comment]
I can merge a single commit pull request which will change only the english lang file (Resources/lang.strings), I've shown your changes in lang_es.strings and lang_pt_BR.strings to the translators (it can't be done from here, your changes will be overwritten with the files from Transifex).

**Comment by mathifonseca** [comment]
Great! I think you should merge two commits from the branch, abaf74a and bd26a35. But it's for you to decide. Thanks!

**Comment by john-preston** [comment]
Thanks! I've merged them and soon they'll be included in the new dev version.

**Comment by mathifonseca** [comment]
Thanks to you!

**Pull request closed without merging**
