### PR TITLE
Add GIFs shared media section

### PR DESCRIPTION
**Pull request by c0re100**
gif-section-ss

Cause empty Gif icon similar to empty photo, so i decided to use `&st::infoEmptyPhoto`.
and thanks @RadRussianRus for fix GIF not opening in fullscreen player in Shared Media.

### CODE REVIEW

**Comment by john-preston** [comment]
I'm not sure this will be rendered well, so many not-so-small GIFs 🙈  But we can test.

**Comment by c0re100** [comment]
> I'm not sure this will be rendered well, so many not-so-small GIFs 🙈 But we can test.

Gif won't play before you click them. 
Cause this section is using `Video` type.
https://github.com/telegramdesktop/tdesktop/pull/8489/commits/1e7ed1b0ec6f1d9b0c099313bc8fc193203e6f4b#diff-8daf15bac38625d0fd5a85d53038543aR918
So preview image won't use too much resource.

**Comment by Neurotoxin001** [comment]
Any news?

**Comment by john-preston** [comment]
@Neurotoxin001 On the official mobile apps the GIFs shared media tab shows all of them animated at once, so I'm afraid it should be done the same way here. And we should see if this could be used well in terms of resources.

**Comment by Neurotoxin001** [comment]
Maybe after moving to 64-bit (https://github.com/telegramdesktop/tdesktop/commit/d97dcaec62a480274533bec90bdb5f63d5a4d7b2) all OOM issues including this will be solved

**Comment by Neurotoxin001** [comment]
Btw, in Kotatogram GIFs is not animated (https://github.com/kotatogram/kotatogram-desktop/commit/67fc24a36b65dfcc67cb38d71bd7425b0ea8b386) maybe just check if "auto play" option is enabled or disabled and use it for GIFs in that section?

**Comment by ilya-fedin** [comment]
> Maybe after moving to 64-bit ([d97dcae](https://github.com/telegramdesktop/tdesktop/commit/d97dcaec62a480274533bec90bdb5f63d5a4d7b2)) all OOM issues including this will be solved

This won't be moving, this will be adding another binary. So the app should still be able to work on 32-bit.

**Comment by Nirzak** [comment]
So, will this feature be implemented. I found this pull request have been opened on 24 August 2020 and now it's April 2021

**Comment by ilya-fedin** [comment]
> So, will this feature be implemented. I found this pull request have been opened on 24 August 2020 and now it's April 2021

Look at the discussion and see that this feature will be too resource consuming and it's most likely forbidden to have non-playable GIFs in the section by someone who higher than preston

**Comment by john-preston** [comment]
@c0re100 As I see right now we already show such amount of autoplayed GIFs in right column:

image

So I think this could be merged if done as mobile apps do (with per-row layout and autoplay, like the Saved GIFs section).

**Review by john-preston — CHANGES_REQUESTED** [review]
I think this could be merged if done as mobile apps do (with per-row layout and autoplay, like the Saved GIFs section).

It should scroll and free resources while scrolling through them not worse than Saved GIFs section in the right column of the same size.

**Comment by john-preston** [comment]
Also, month dividers could be added (the same as photos / video files), that way there will be less GIFs on one screen.

**Comment by Aokromes** [comment]
@c0re100

**Comment by c0re100** [comment]
Sorry, due to some life problem, I don't have time to finish this work :(

**Comment by 23rd** [comment]
I think I'll handle it if no one else will.

**Pull request closed without merging**
