### PR TITLE
Remove rounded rectangle message bubble style

### PR DESCRIPTION
**Pull request by wbsdty331**
added signature.

* advise 1

`macOS` version use Rounded rectangle style
`Windows` & `Linux` keep original style.

* advise 2

make it optional.
If you like rounded rectangle bubble style, Just enable it.

Which do you prefer?

### CODE REVIEW

**Comment by matteocontrini** [comment]
Can you post a screenshot of how this "3px" rounded style looks exactly?

**Comment by wbsdty331** [comment]
Please use 0.9.56 Version
That's normal message bubble style.

**Comment by lgommans** [comment]
Can someone with commit access please give us an update on this? Like, it's a config file change, it can't break anything. Can we merge this already or are there still considerations to be made?

**Comment by Geobert** [comment]
What are we waiting for?

**Comment by nocturnal3d** [comment]
+1 👍

**Comment by wbsdty331** [comment]
Nope?

**Comment by chermenin** [comment]
Old style of messages really better. Give it back!

**Comment by daslapovsky** [comment]
+1 for old style.

**Comment by Akiyamka** [comment]
Now the rounded corners look very clumsy. Old design telegram though was nothing special, but it was rather restrained so as not to annoy the user. Let's return everything as it was, and experimentation with alternative themes design leave registration

**Pull request closed without merging**
