### PR TITLE
changed icon to new logo #7891

### PR DESCRIPTION
**Pull request by maxwxyz**
Updated the outdated icon/logo of the desktop client to the current one.

### CODE REVIEW

**Comment by Aokromes** [comment]
i think you need  to add all res png files and not only .ico file.

**Comment by 23rd** [comment]
I think it will not be merged anyway.

**Comment by maxwxyz** [comment]
I added also all res png files.
Why would it not be merged? @23rd

**Comment by 23rd** [comment]
Such a fundamental thing as the application icon is handled by the Telegram team itself and their designers, no one else.

**Comment by john-preston** [comment]
The icon for macOS was not updated. But indeed, when the designer that works with my app says I need to update it and sends the exact artworks - I will. Sorry.

**Pull request closed without merging**
