### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by 23rd** [comment]
Oh no, this is going to turn into a generator of tons of garbage. =(

There are not so much Github actions to keep them up to date.

**Comment by ilya-fedin** [comment]
> Oh no, this is going to turn into a generator of tons of garbage. =(

You think? There's not so much external actions in use. I actually myself though about that as manual bumping of e.g. no-response bot is a routine.

**Comment by ilya-fedin** [comment]
But the author account looks suspicious, there's two PRs from accounts having 'Naveen' in name and none of them signed the CLA

**Comment by naveensrinivasan** [comment]
The idea was to help. I understand if you don’t want it. Thanks

**Comment by ilya-fedin** [comment]
Well, personally I like this, I wonder what @john-preston thinks

**Pull request closed without merging**
