### PR TITLE
Add hime inputcontext plugin for linux version

### PR DESCRIPTION
**Pull request by Zankio**
Add hime support (#3129)

Signed-off-by: Zankio <xxoojoeooxx1@gmail.com>
(github: zankio)

### CODE REVIEW

**Comment by john-preston** [comment]
Thanks! And where does this code (that was added to qt patch) come from? Can I see the original somewhere?

**Comment by Zankio** [comment]
I am so sorry.
I think I have some misunderstanding about public domain.
Could I revert this pull request?
How can i do?

**Comment by john-preston** [comment]
@Zankio I can remove this code from the  next version if this is a problem.

What is the license of this input context plugin code?

**Comment by stek29** [comment]
If it's from [hime-ime/hime](https://github.com/hime-ime/hime), then [it seems to be](https://github.com/hime-ime/hime/blob/3f52703feab6e1e81ce01a18e5ff59d4e7355c53/src/qt-im/qhimeinputcontextplugin.h) "Your Qt License", Q Public License or GPL v2 (not 2 and newer)

**Comment by john-preston** [comment]
Your Qt License is fine for me :) I guess I can put parts of LGPL-licensed code in the patch.

@Zankio if it is a problem that this code was added by you with granting it into public domain then I can remove those changes (revert the patch) and then add them myself respecting the same Qt license that is used for Qt in Telegram Desktop.

**Comment by Zankio** [comment]
Yes, it is from [hime-ime/hime](https://github.com/hime-ime/hime).

In README.md, the license of hime is 
> 授權 (License)
> LGPLv2.1 (Qt immodules are GPLv2)

The code which was added by me is include 
* hime/src (LGPL v2.1)
* hime/src/im-client (LGPL v2.1)
* hime/src/qt5-im (?)

I am not sure the license of `qt5-im`. GPL v2?
`qt5-im` code is come from gcin which is LGPL v2.1.

I should contact someone in order to check the license of `qt5-im`.

@john-preston  Thank you.

**Comment by john-preston** [comment]
@Zankio Ok, it looks at least legit to have this code inside this repository. Please reach if you'll find out something more about the qt5-im code.

**Pull request merged**
